/* Generated By:JavaCC: Do not edit this line. DUDE_ParserConstants.java */
package org.dllearner.algorithm.tbsl.sem.dudes.reader;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DUDE_ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EVERY = 16;
  /** RegularExpression Id. */
  int MOST = 17;
  /** RegularExpression Id. */
  int SOME = 18;
  /** RegularExpression Id. */
  int THEMOST = 19;
  /** RegularExpression Id. */
  int THELEAST = 20;
  /** RegularExpression Id. */
  int AFEW = 21;
  /** RegularExpression Id. */
  int MANY = 22;
  /** RegularExpression Id. */
  int NO = 23;
  /** RegularExpression Id. */
  int OR = 24;
  /** RegularExpression Id. */
  int HOWMANY = 25;
  /** RegularExpression Id. */
  int LABEL = 26;
  /** RegularExpression Id. */
  int A = 27;
  /** RegularExpression Id. */
  int B = 28;
  /** RegularExpression Id. */
  int C = 29;
  /** RegularExpression Id. */
  int QUOTED_STRING = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"<\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\">\"",
    "\"=\"",
    "\"res(\"",
    "\")\"",
    "\"scope(\"",
    "\"(\"",
    "\":[\"",
    "\"|\"",
    "\"NOT\"",
    "\"/\"",
    "\"^\"",
    "\"EVERY\"",
    "\"MOST\"",
    "\"SOME\"",
    "\"THEMOST\"",
    "\"THELEAST\"",
    "\"AFEW\"",
    "\"MANY\"",
    "\"NO\"",
    "\"OR\"",
    "\"HOWMANY\"",
    "<LABEL>",
    "<A>",
    "<B>",
    "<C>",
    "<QUOTED_STRING>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
