
package org.dllearner.server.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1
 * Generated source version: 2.1.1
 * 
 */
@XmlRootElement(name = "LearningProblemUnsupportedException", namespace = "http://server.dllearner.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LearningProblemUnsupportedException", namespace = "http://server.dllearner.org/")
public class LearningProblemUnsupportedExceptionBean {

    private String message;

    /**
     * 
     * @return
     *     returns String
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * 
     * @param message
     *     the value for the message property
     */
    public void setMessage(String message) {
        this.message = message;
    }

}
