/* Generated By:JavaCC: Do not edit this line. ConfParserConstants.java */
package org.dllearner.confparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ConfParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int COMMAND_END = 8;
  /** RegularExpression Id. */
  int CONF_END = 9;
  /** RegularExpression Id. */
  int POS_EX = 10;
  /** RegularExpression Id. */
  int NEG_EX = 11;
  /** RegularExpression Id. */
  int ID = 12;
  /** RegularExpression Id. */
  int NUMBER = 13;
  /** RegularExpression Id. */
  int DOUBLE = 14;
  /** RegularExpression Id. */
  int TOP = 15;
  /** RegularExpression Id. */
  int BOTTOM = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int OR = 18;
  /** RegularExpression Id. */
  int EXISTS = 19;
  /** RegularExpression Id. */
  int ALL = 20;
  /** RegularExpression Id. */
  int NOT = 21;
  /** RegularExpression Id. */
  int GE = 22;
  /** RegularExpression Id. */
  int LE = 23;
  /** RegularExpression Id. */
  int STRING = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\".\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "<ID>",
    "<NUMBER>",
    "<DOUBLE>",
    "\"TOP\"",
    "\"BOTTOM\"",
    "\"AND\"",
    "\"OR\"",
    "<EXISTS>",
    "<ALL>",
    "<NOT>",
    "\">=\"",
    "\"<=\"",
    "<STRING>",
    "\"=\"",
    "\"{\"",
    "\"[\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"}\"",
    "\"]\"",
  };

}
