/* Generated By:JavaCC: Do not edit this line. DRSParserConstants.java */
package org.dllearner.algorithm.tbsl.sem.drs.reader;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DRSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EVERY = 10;
  /** RegularExpression Id. */
  int MOST = 11;
  /** RegularExpression Id. */
  int SOME = 12;
  /** RegularExpression Id. */
  int THEMOST = 13;
  /** RegularExpression Id. */
  int THELEAST = 14;
  /** RegularExpression Id. */
  int AFEW = 15;
  /** RegularExpression Id. */
  int MANY = 16;
  /** RegularExpression Id. */
  int NO = 17;
  /** RegularExpression Id. */
  int HOWMANY = 18;
  /** RegularExpression Id. */
  int LABEL = 19;
  /** RegularExpression Id. */
  int A = 20;
  /** RegularExpression Id. */
  int B = 21;
  /** RegularExpression Id. */
  int C = 22;
  /** RegularExpression Id. */
  int QUOTED_STRING = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\":\"",
    "\"[\"",
    "\"|\"",
    "\"]\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"NOT\"",
    "\"EVERY\"",
    "\"MOST\"",
    "\"SOME\"",
    "\"THEMOST\"",
    "\"THELEAST\"",
    "\"AFEW\"",
    "\"MANY\"",
    "\"NO\"",
    "\"HOWMANY\"",
    "<LABEL>",
    "<A>",
    "<B>",
    "<C>",
    "<QUOTED_STRING>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
