/* Generated By:JJTree: Do not edit this line. ./ConfParserTreeConstants.java */

package org.dllearner.parser;

public @SuppressWarnings("all") interface ConfParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTCONFOPTION = 1;
  public int JJTFUNCTIONCALL = 2;
  public int JJTPOSEXAMPLE = 3;
  public int JJTNEGEXAMPLE = 4;
  public int JJTINDIVIDUAL = 5;
  public int JJTID = 6;
  public int JJTDOUBLE = 7;
  public int JJTINTEGER = 8;
  public int JJTSTRING = 9;


  public String[] jjtNodeName = {
    "Start",
    "ConfOption",
    "FunctionCall",
    "PosExample",
    "NegExample",
    "Individual",
    "Id",
    "Double",
    "Integer",
    "String",
  };
}
