/* Generated By:JJTree&JavaCC: Do not edit this line. DLLearner.java */
package org.dllearner.parser;

import java.util.List;
import java.util.LinkedList;
import java.util.Map;
import java.util.TreeMap;
import java.util.Set;
import java.util.HashSet;
import java.util.SortedSet;
import java.util.TreeSet;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.StringReader;

import org.dllearner.Main;
import org.dllearner.Info;

import org.dllearner.core.dl.*;
import org.dllearner.ConfigurationOption;
import org.dllearner.utilities.*;

// @SuppressWarnings({"all"})
public @SuppressWarnings("all") class DLLearner/*@bgen(jjtree)*/implements DLLearnerTreeConstants, DLLearnerConstants {/*@bgen(jjtree)*/
  protected JJTDLLearnerState jjtree = new JJTDLLearnerState();
        private static ConceptComparator conceptComparator = new ConceptComparator();
        // hier wird Parse-Fehler angezeigt, obwohl eigentlich alles stimmt??
        private Map<AtomicConcept,SortedSet<Individual>> positiveExamples = new TreeMap<AtomicConcept,SortedSet<Individual>>(conceptComparator);
        private Map<AtomicConcept,SortedSet<Individual>> negativeExamples = new TreeMap<AtomicConcept,SortedSet<Individual>>(conceptComparator);

        // Konfigurationsoptionen
        private List<ConfigurationOption> confOptions = new LinkedList<ConfigurationOption>();

        // Funktionsaufrufe (die gleiche Funktion darf mehrmals mit unterschiedlichen
        // Argumenten aufgerufen werden)
        // private static Map<String,Set<String>> functionCallsAlt = new TreeMap<String,Set<String>>();
        // jeder Funktionsaufruf hat eine Liste von n Argumenten; alle Funktionsaufrufe
        // werden in einer Liste gespeichert
        private List<List<String>> functionCalls = new LinkedList<List<String>>();
        // => irgendwie Funktionsname + Argumente speichern
        // => d.h. man bräuchte für jede Funktion so eine Liste oder das erste Element
        // der Liste ist der Funktionsname <= ist noch die praktikabelste Variante

        // speichert, ob der Parser-Konstruktor aufgerufen wurde: momemtan handelt es
        // sich um einen statischen Parser, d.h. der Konstruktor darf nur einmal
        // aufgerufen werden; weitere Parsevorgänge erfolgen dann mit ReInit
        // TODO: bei einem Webservice braucht man wahrscheinlich einen dynamischen Parser
        // private static boolean constructorCalled = false;

        // Wissensbasis
        private KB kb = new KB();
        public static final String internalNamespace = "http://localhost/foo#";

        private void addPositiveExample(AtomicConcept conceptName, Individual instanceName) {
                if(positiveExamples.containsKey(conceptName)) {
                        positiveExamples.get(conceptName).add(instanceName);
                } else {
                        SortedSet<Individual> newTarget = new TreeSet<Individual>();
                        newTarget.add(instanceName);
                        positiveExamples.put(conceptName,newTarget);
                }
        }

        private void addNegativeExample(AtomicConcept conceptName, Individual instanceName) {
                if(negativeExamples.containsKey(conceptName)) {
                        negativeExamples.get(conceptName).add(instanceName);
                } else {
                        SortedSet<Individual> newTarget = new TreeSet<Individual>();
                        newTarget.add(instanceName);
                        negativeExamples.put(conceptName,newTarget);
                }
        }

        public Map<AtomicConcept,SortedSet<Individual>> getPositiveExamples() {
                return positiveExamples;
        }

        public Map<AtomicConcept,SortedSet<Individual>> getNegativeExamples() {
                return negativeExamples;
        }

        public List<ConfigurationOption> getConfOptions() {
                return confOptions;
        }

        public List<List<String>> getFunctionCalls() {
                return functionCalls;
        }

        public KB getKB() {
                return kb;
        }

        /*
	private static void addFunctionCall(String functionName, String argument) {
		if(functionCalls.containsKey(functionName)) {
			functionCalls.get(functionName).add(argument);
		} else {
			Set<String> newFunction = new TreeSet<String>();
			newFunction.add(argument);
			functionCalls.put(functionName,newFunction);
		}		
	}
	*/

        // Methode um allen internen Sachen eine URI zu geben (ist zwar für DLs nicht
        // notwendig, aber bei Ontologien schon und die interne KB soll eine Ontologie
        // repräsentieren
        public static String getInternalURI(String name) {
                if(name.startsWith("http://"))
                        return name;
                else
                        return internalNamespace + name;
        }

        public static SimpleNode parseString(String str) throws ParseException {
                StringReader sr = new StringReader(str);
                DLLearner learner = new DLLearner(sr);
                SimpleNode n = learner.Start();
                return n;
        }

        public static Concept parseConcept(String str) throws ParseException {
                StringReader sr = new StringReader(str);
                DLLearner learner = new DLLearner(sr);
                // 		
                //SimpleNode n = DLLearner.Start();
                //return n;	
                /*
		Concept c = null;	
		try {

			c = DLLearner.Concept();
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}*/
                Concept c = learner.Concept();

                return c;
        }

        public static DLLearner parseFile(String filename) {
                DLLearner learner = null;
                try {
                        learner = new DLLearner(new FileInputStream(filename));
                        learner.Start();
                } catch(FileNotFoundException e) {
                        e.printStackTrace();
                } catch(ParseException e) {
                        e.printStackTrace();
                }
                return learner;
        }

  public static void main(String args[]) {

    if(args.length==0) {
        System.out.println("Please specify an input file.");
        System.exit(0);
    }

    System.out.println("Starting DL-Learner (Build " + Info.build + ")");
        // System.out.println(args);

        // System.out.println(args[0]);
        // System.out.println(args[1]);
        // System.out.println(args.length);

    File f = new File(args[args.length-1]);
    String baseDir = "";

        System.out.print("Parsing " + f.getName() + " ... ");
    long parseStartTime = System.currentTimeMillis();

    SimpleNode n = null;
    DLLearner learner = null;
    try {
        learner = new DLLearner(new FileInputStream(args[args.length-1]));
        baseDir = f.getParentFile().getPath();
    } catch(IOException e) {
        System.err.println(e);
        System.exit(0);
    }
    try {
      n = learner.Start();
      // n.dump("");
      // System.out.println("Thank you.");
    } catch (Exception e) {
      System.out.println("\nParse exception occurred. Please follow the advise given below.");
      System.out.println(e.getMessage());
      e.printStackTrace();
      System.exit(0);
    }

    long parseDuration = System.currentTimeMillis() - parseStartTime;
    System.out.println("OK (" + parseDuration + " ms)");

    boolean queryMode = false;
    // solution test mode wird nicht unbedingt gebraucht, da man die covers
    // gleich standardmäßig beim query mit anzeigen kann
    // boolean solutionTestMode = false;

    if(args.length>1 && args[0].equals("-q"))
        queryMode = true;

    //if(args.length>1 && args[0].equals("-qt")) {
    //	queryMode = true;
    //	solutionTestMode = true;
    //}

    // new Main(n, baseDir, queryMode);
    // Parser erstmal Standalone testen
    // n.dump("");

    // neuer Aufruf des Hauptprogramms
    // TODO: remove (in the future, the parser will be called from whatever method
    // needs it, instead of starting the learning process itself)
    // new Main(kb,positiveExamples,negativeExamples,confOptions,functionCalls,baseDir,queryMode);
  }

/* Grob�berblick:
  	 	Id() [ "." Id() ] "="  ( Id() | Number() ) <CONF_END>	// Konfigurationsoption
  	|	Id() "(" String() ")" <CONF_END>
  	| 	<POS_EX> Id() "(" Id() ")" <COMMAND_END>  	// positives Beispiel
  	|	<NEG_EX> Id() "(" Id() ")" <COMMAND_END>  	// negatives Beispiel
  	|	Id() "(" Id() "," Id() ")" <COMMAND_END>  	// ABox - Rolle
  	|	Concept() "(" Id() ")" <COMMAND_END>     	// ABox - Konzept
  	|	"Transitive" + "(" + Id() ")" <COMMAND_END>		// transitive Rollen, analog transitiv, funktional
  	|	"Inverse" + "(" + Id() + "," + Id() + ")" <COMMAND_END>	// Rolle 1 invers zu Rolle 2
  	|	"Subrole" + "(" + Id() + "," + Id() + ")" <COMMAND_END>	// Rolle 1 Teilmenge von Rolle 2
  	|	Concept() "=" Concept() <COMMAND_END>		// TBox - �quivalenz von Konzepten
  	|	Concept() "SUBCLASS" Concept() <COMMAND_END> 	// TBox - Konzept 1 Teilmenge von Konzept 2
*/
  final public SimpleNode Start() throws ParseException {
 /*@bgen(jjtree) Start */
        SimpleNode jjtn000 = new SimpleNode(JJTSTART);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);ConceptAssertion conceptAssertion;
        RoleAssertion roleAssertion;
        RBoxAxiom rBoxAxiom;
        Equality equality;
        Inclusion inclusion;
        ConfigurationOption confOption;
    try {
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case POS_EX:
        case NEG_EX:
        case ID:
        case TOP:
        case BOTTOM:
        case EXISTS:
        case ALL:
        case NOT:
        case GE:
        case LE:
        case STRING:
        case 29:
        case 33:
        case 34:
        case 35:
        case 36:
        case 37:
          ;
          break;
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
        if (jj_2_1(2147483647)) {
          confOption = ConfOption();
                    confOptions.add(confOption);
        } else if (jj_2_2(2147483647)) {
          FunctionCall();
        } else if (jj_2_3(2147483647)) {
          PosExample();
        } else if (jj_2_4(2147483647)) {
          NegExample();
        } else if (jj_2_5(2147483647)) {
          conceptAssertion = ABoxConcept();
                  kb.addABoxAxiom(conceptAssertion);
        } else if (jj_2_6(2147483647)) {
          roleAssertion = ABoxRole();
                  kb.addABoxAxiom(roleAssertion);
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case 33:
            rBoxAxiom = Transitive();
                  kb.addRBoxAxiom(rBoxAxiom);
            break;
          case 34:
            rBoxAxiom = Functional();
                  kb.addRBoxAxiom(rBoxAxiom);
            break;
          case 35:
            rBoxAxiom = Symmetric();
                  kb.addRBoxAxiom(rBoxAxiom);
            break;
          case 36:
            rBoxAxiom = Inverse();
                  kb.addRBoxAxiom(rBoxAxiom);
            break;
          case 37:
            rBoxAxiom = Subrole();
                  kb.addRBoxAxiom(rBoxAxiom);
            break;
          default:
            jj_la1[1] = jj_gen;
            if (jj_2_7(2147483647)) {
              equality = TBoxEquiv();
                  kb.addTBoxAxiom(equality);
            } else if (jj_2_8(2147483647)) {
              inclusion = TBoxSub();
                  kb.addTBoxAxiom(inclusion);
            } else {
              jj_consume_token(-1);
              throw new ParseException();
            }
          }
        }
      }
      jj_consume_token(0);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return jjtn000;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public KB parseKB() throws ParseException {
 /*@bgen(jjtree) parseKB */
        SimpleNode jjtn000 = new SimpleNode(JJTPARSEKB);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);KB kb = null;
    try {
      jj_consume_token(0);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
         {if (true) return kb;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
    throw new Error("Missing return statement in function");
  }

  final public ConfigurationOption ConfOption() throws ParseException {
 /*@bgen(jjtree) ConfOption */
        SimpleNode jjtn000 = new SimpleNode(JJTCONFOPTION);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);boolean containsSubOption=false, isNumeric=false, isDouble=false, isSet=false;
        String option="", subOption="", value="", tmp="";
        int number = 0;
        double numberDouble = 0;
        ConfigurationOption confOption;
        Set<String> values = new HashSet<String>();
    try {
      option = Id();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMAND_END:
        jj_consume_token(COMMAND_END);
        subOption = Id();
                                    containsSubOption=true;
        break;
      default:
        jj_la1[2] = jj_gen;
        ;
      }
      jj_consume_token(25);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ID:
        value = Id();
        break;
      case STRING:
        value = String();
        break;
      case NUMBER:
        number = Integer();
                             isNumeric=true;
        break;
      case DOUBLE:
        numberDouble = Double();
                                  isNumeric=true; isDouble=true;
        break;
      default:
        jj_la1[5] = jj_gen;
        if (jj_2_10(2147483647)) {
          jj_consume_token(26);
          jj_consume_token(27);
                                       isSet=true;
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case 26:
            jj_consume_token(26);
            label_2:
            while (true) {
              if (jj_2_9(2)) {
                ;
              } else {
                break label_2;
              }
              switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
              case STRING:
                tmp = String();
                break;
              case ID:
                tmp = Id();
                break;
              default:
                jj_la1[3] = jj_gen;
                jj_consume_token(-1);
                throw new ParseException();
              }
                                                           values.add(tmp);
              jj_consume_token(28);
            }
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case STRING:
              tmp = String();
              break;
            case ID:
              tmp = Id();
              break;
            default:
              jj_la1[4] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
                                      values.add(tmp);
            jj_consume_token(27);
                                                             isSet=true;
            break;
          default:
            jj_la1[6] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
      jj_consume_token(CONF_END);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
        if(containsSubOption) {
                if(isNumeric)
                        if(isDouble)
                                confOption = new ConfigurationOption(option,subOption,numberDouble);
                        else
                                confOption = new ConfigurationOption(option,subOption,number);
                else
                        if(isSet)
                                confOption = new ConfigurationOption(option,subOption,values);
                        else
                                confOption = new ConfigurationOption(option,subOption,value);
        } else {
                if(isNumeric)
                        if(isDouble)
                                confOption = new ConfigurationOption(option,numberDouble);
                        else
                                confOption = new ConfigurationOption(option,number);
                else
                        if(isSet)
                                confOption = new ConfigurationOption(option,values);
                        else
                                confOption = new ConfigurationOption(option,value);
        }
        {if (true) return confOption;}
        // confOptions.add(confOption);

    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public void FunctionCall() throws ParseException {
 /*@bgen(jjtree) FunctionCall */
        SimpleNode jjtn000 = new SimpleNode(JJTFUNCTIONCALL);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);String s, s1, s2;
        List<String> list = new LinkedList<String>();
    try {
      s1 = Id();
      jj_consume_token(29);
      s2 = String();
                                  list.add(s1); list.add(s2);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 28:
          ;
          break;
        default:
          jj_la1[7] = jj_gen;
          break label_3;
        }
        jj_consume_token(28);
        s = String();
                          list.add(s);
      }
      jj_consume_token(30);
      jj_consume_token(CONF_END);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
          functionCalls.add(list);
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  final public void PosExample() throws ParseException {
                     /*@bgen(jjtree) PosExample */
                      SimpleNode jjtn000 = new SimpleNode(JJTPOSEXAMPLE);
                      boolean jjtc000 = true;
                      jjtree.openNodeScope(jjtn000);AtomicConcept ac; Individual i;
    try {
      jj_consume_token(POS_EX);
      ac = AtomicConcept();
      jj_consume_token(29);
      i = Individual();
      jj_consume_token(30);
      jj_consume_token(COMMAND_END);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
          addPositiveExample(ac,i);
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  final public void NegExample() throws ParseException {
                     /*@bgen(jjtree) NegExample */
                      SimpleNode jjtn000 = new SimpleNode(JJTNEGEXAMPLE);
                      boolean jjtc000 = true;
                      jjtree.openNodeScope(jjtn000);AtomicConcept ac; Individual i;
    try {
      jj_consume_token(NEG_EX);
      ac = AtomicConcept();
      jj_consume_token(29);
      i = Individual();
      jj_consume_token(30);
      jj_consume_token(COMMAND_END);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
          addNegativeExample(ac,i);
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  final public ConceptAssertion ABoxConcept() throws ParseException {
                                  /*@bgen(jjtree) ABoxConcept */
                                  SimpleNode jjtn000 = new SimpleNode(JJTABOXCONCEPT);
                                  boolean jjtc000 = true;
                                  jjtree.openNodeScope(jjtn000);Concept c; Individual i;
    try {
      c = Concept();
      jj_consume_token(29);
      i = Individual();
      jj_consume_token(30);
      jj_consume_token(COMMAND_END);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
          {if (true) return new ConceptAssertion(c,i);}
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
    throw new Error("Missing return statement in function");
  }

  final public RoleAssertion ABoxRole() throws ParseException {
 /*@bgen(jjtree) ABoxRole */
        SimpleNode jjtn000 = new SimpleNode(JJTABOXROLE);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);boolean isNegated=false;
        AtomicRole ar;
        Individual i1,i2;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NOT:
        Not();
                isNegated=true;
        break;
      default:
        jj_la1[8] = jj_gen;
        ;
      }
      ar = AtomicRole();
      jj_consume_token(29);
      i1 = Individual();
      jj_consume_token(28);
      i2 = Individual();
      jj_consume_token(30);
      jj_consume_token(COMMAND_END);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
                if(isNegated)
                        {if (true) throw new Error("negated role assertions not supported yet");}
                else
                        {if (true) return new RoleAssertion(ar,i1,i2);}
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
    throw new Error("Missing return statement in function");
  }

  final public TransitiveRoleAxiom Transitive() throws ParseException {
                                    /*@bgen(jjtree) Transitive */
                                    SimpleNode jjtn000 = new SimpleNode(JJTTRANSITIVE);
                                    boolean jjtc000 = true;
                                    jjtree.openNodeScope(jjtn000);AtomicRole ar;
    try {
      jj_consume_token(33);
      jj_consume_token(29);
      ar = AtomicRole();
      jj_consume_token(30);
      jj_consume_token(COMMAND_END);
     jjtree.closeNodeScope(jjtn000, true);
     jjtc000 = false;
     {if (true) return new TransitiveRoleAxiom(ar);}
    } catch (Throwable jjte000) {
     if (jjtc000) {
       jjtree.clearNodeScope(jjtn000);
       jjtc000 = false;
     } else {
       jjtree.popNode();
     }
     if (jjte000 instanceof RuntimeException) {
       {if (true) throw (RuntimeException)jjte000;}
     }
     if (jjte000 instanceof ParseException) {
       {if (true) throw (ParseException)jjte000;}
     }
     {if (true) throw (Error)jjte000;}
    } finally {
     if (jjtc000) {
       jjtree.closeNodeScope(jjtn000, true);
     }
    }
    throw new Error("Missing return statement in function");
  }

  final public FunctionalRoleAxiom Functional() throws ParseException {
                                    /*@bgen(jjtree) Functional */
                                    SimpleNode jjtn000 = new SimpleNode(JJTFUNCTIONAL);
                                    boolean jjtc000 = true;
                                    jjtree.openNodeScope(jjtn000);AtomicRole ar;
    try {
      jj_consume_token(34);
      jj_consume_token(29);
      ar = AtomicRole();
      jj_consume_token(30);
      jj_consume_token(COMMAND_END);
     jjtree.closeNodeScope(jjtn000, true);
     jjtc000 = false;
     {if (true) return new FunctionalRoleAxiom(ar);}
    } catch (Throwable jjte000) {
     if (jjtc000) {
       jjtree.clearNodeScope(jjtn000);
       jjtc000 = false;
     } else {
       jjtree.popNode();
     }
     if (jjte000 instanceof RuntimeException) {
       {if (true) throw (RuntimeException)jjte000;}
     }
     if (jjte000 instanceof ParseException) {
       {if (true) throw (ParseException)jjte000;}
     }
     {if (true) throw (Error)jjte000;}
    } finally {
     if (jjtc000) {
       jjtree.closeNodeScope(jjtn000, true);
     }
    }
    throw new Error("Missing return statement in function");
  }

  final public SymmetricRoleAxiom Symmetric() throws ParseException {
                                  /*@bgen(jjtree) Symmetric */
                                  SimpleNode jjtn000 = new SimpleNode(JJTSYMMETRIC);
                                  boolean jjtc000 = true;
                                  jjtree.openNodeScope(jjtn000);AtomicRole ar;
    try {
      jj_consume_token(35);
      jj_consume_token(29);
      ar = AtomicRole();
      jj_consume_token(30);
      jj_consume_token(COMMAND_END);
     jjtree.closeNodeScope(jjtn000, true);
     jjtc000 = false;
     {if (true) return new SymmetricRoleAxiom(ar);}
    } catch (Throwable jjte000) {
     if (jjtc000) {
       jjtree.clearNodeScope(jjtn000);
       jjtc000 = false;
     } else {
       jjtree.popNode();
     }
     if (jjte000 instanceof RuntimeException) {
       {if (true) throw (RuntimeException)jjte000;}
     }
     if (jjte000 instanceof ParseException) {
       {if (true) throw (ParseException)jjte000;}
     }
     {if (true) throw (Error)jjte000;}
    } finally {
     if (jjtc000) {
       jjtree.closeNodeScope(jjtn000, true);
     }
    }
    throw new Error("Missing return statement in function");
  }

  final public InverseRoleAxiom Inverse() throws ParseException {
                              /*@bgen(jjtree) Inverse */
                              SimpleNode jjtn000 = new SimpleNode(JJTINVERSE);
                              boolean jjtc000 = true;
                              jjtree.openNodeScope(jjtn000);AtomicRole ar1,ar2;
    try {
      jj_consume_token(36);
      jj_consume_token(29);
      ar1 = AtomicRole();
      jj_consume_token(28);
      ar2 = AtomicRole();
      jj_consume_token(30);
      jj_consume_token(COMMAND_END);
     jjtree.closeNodeScope(jjtn000, true);
     jjtc000 = false;
     {if (true) return new InverseRoleAxiom(ar1,ar2);}
    } catch (Throwable jjte000) {
     if (jjtc000) {
       jjtree.clearNodeScope(jjtn000);
       jjtc000 = false;
     } else {
       jjtree.popNode();
     }
     if (jjte000 instanceof RuntimeException) {
       {if (true) throw (RuntimeException)jjte000;}
     }
     if (jjte000 instanceof ParseException) {
       {if (true) throw (ParseException)jjte000;}
     }
     {if (true) throw (Error)jjte000;}
    } finally {
     if (jjtc000) {
       jjtree.closeNodeScope(jjtn000, true);
     }
    }
    throw new Error("Missing return statement in function");
  }

  final public SubRoleAxiom Subrole() throws ParseException {
                          /*@bgen(jjtree) Subrole */
                          SimpleNode jjtn000 = new SimpleNode(JJTSUBROLE);
                          boolean jjtc000 = true;
                          jjtree.openNodeScope(jjtn000);AtomicRole ar1,ar2;
    try {
      jj_consume_token(37);
      jj_consume_token(29);
      ar1 = AtomicRole();
      jj_consume_token(28);
      ar2 = AtomicRole();
      jj_consume_token(30);
      jj_consume_token(COMMAND_END);
     jjtree.closeNodeScope(jjtn000, true);
     jjtc000 = false;
     {if (true) return new SubRoleAxiom(ar1,ar2);}
    } catch (Throwable jjte000) {
     if (jjtc000) {
       jjtree.clearNodeScope(jjtn000);
       jjtc000 = false;
     } else {
       jjtree.popNode();
     }
     if (jjte000 instanceof RuntimeException) {
       {if (true) throw (RuntimeException)jjte000;}
     }
     if (jjte000 instanceof ParseException) {
       {if (true) throw (ParseException)jjte000;}
     }
     {if (true) throw (Error)jjte000;}
    } finally {
     if (jjtc000) {
       jjtree.closeNodeScope(jjtn000, true);
     }
    }
    throw new Error("Missing return statement in function");
  }

/******* PARSER OHNE EIGENE METHODEN FÜR ATOMIC CONCEPT/ROLE *** DEPRECATED
void PosExample() : {String s1="",s2="";}
{
  	<POS_EX> (s1=Id()|s1=String()) "(" (s2=Id()|s2=String()) ")" <COMMAND_END>
  	{ addPositiveExample(s1,s2); }
}

void NegExample() : {String s1="",s2="";}
{
  	<NEG_EX> [s1=Id()|s1=String()] "(" [s2=Id()|s2=String()] ")" <COMMAND_END>
  	{ addNegativeExample(s1,s2); }
}

ConceptAssertion ABoxConcept() : {Concept c; String s;}
{
	c=Concept() "(" s=Id() ")" <COMMAND_END>
	{ return new ConceptAssertion(c,s); }	
}

RoleAssertion ABoxRole() : { boolean isNegated=false; String s1,s2,s3;}
{
   	[Not() {isNegated=true;}] s1=Id() "(" s2=Id() "," s3=Id() ")" <COMMAND_END>
   	{
   		if(isNegated)
   			throw new Error("negated role assertions not supported yet");
   		else
   			return new RoleAssertion(new AtomicRole(s1),s2,s3);
   	}
}

TransitiveRoleAxiom Transitive() : {String s;}
{
   "Transitive" "(" s=Id() ")" <COMMAND_END>
   { return new TransitiveRoleAxiom(new AtomicRole(s)); }
}

FunctionalRoleAxiom Functional() : {String s;}
{
   "Functional" "(" s=Id() ")" <COMMAND_END>
   { return new FunctionalRoleAxiom(new AtomicRole(s)); }
   
}

SymmetricRoleAxiom Symmetric() : {String s;}
{
   "Symmetric" "(" s=Id() ")" <COMMAND_END>
   { return new SymmetricRoleAxiom(new AtomicRole(s)); }
}

InverseRoleAxiom Inverse() : {String s1,s2;}
{
   "Inverse" "(" s1=Id() "," s2=Id() ")" <COMMAND_END>
   { return new InverseRoleAxiom(new AtomicRole(s1),new AtomicRole(s2)); }
}

SubRoleAxiom Subrole() : {String s1,s2;}
{
   "Subrole" "(" s1=Id() "," s2=Id() ")" <COMMAND_END>
   { return new SubRoleAxiom(new AtomicRole(s1),new AtomicRole(s2));}
}
****************************************************************/
  final public Equality TBoxEquiv() throws ParseException {
                        /*@bgen(jjtree) TBoxEquiv */
                        SimpleNode jjtn000 = new SimpleNode(JJTTBOXEQUIV);
                        boolean jjtc000 = true;
                        jjtree.openNodeScope(jjtn000);Concept c1,c2;
    try {
      c1 = Concept();
      jj_consume_token(25);
      c2 = Concept();
      jj_consume_token(COMMAND_END);
     jjtree.closeNodeScope(jjtn000, true);
     jjtc000 = false;
     {if (true) return new Equality(c1,c2);}
    } catch (Throwable jjte000) {
     if (jjtc000) {
       jjtree.clearNodeScope(jjtn000);
       jjtc000 = false;
     } else {
       jjtree.popNode();
     }
     if (jjte000 instanceof RuntimeException) {
       {if (true) throw (RuntimeException)jjte000;}
     }
     if (jjte000 instanceof ParseException) {
       {if (true) throw (ParseException)jjte000;}
     }
     {if (true) throw (Error)jjte000;}
    } finally {
     if (jjtc000) {
       jjtree.closeNodeScope(jjtn000, true);
     }
    }
    throw new Error("Missing return statement in function");
  }

  final public Inclusion TBoxSub() throws ParseException {
                       /*@bgen(jjtree) TBoxSub */
                       SimpleNode jjtn000 = new SimpleNode(JJTTBOXSUB);
                       boolean jjtc000 = true;
                       jjtree.openNodeScope(jjtn000);Concept c1,c2;
    try {
      c1 = Concept();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 31:
        jj_consume_token(31);
        break;
      case 32:
        jj_consume_token(32);
        break;
      case 38:
        jj_consume_token(38);
        break;
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      c2 = Concept();
      jj_consume_token(COMMAND_END);
     jjtree.closeNodeScope(jjtn000, true);
     jjtc000 = false;
     {if (true) return new Inclusion(c1,c2);}
    } catch (Throwable jjte000) {
     if (jjtc000) {
       jjtree.clearNodeScope(jjtn000);
       jjtc000 = false;
     } else {
       jjtree.popNode();
     }
     if (jjte000 instanceof RuntimeException) {
       {if (true) throw (RuntimeException)jjte000;}
     }
     if (jjte000 instanceof ParseException) {
       {if (true) throw (ParseException)jjte000;}
     }
     {if (true) throw (Error)jjte000;}
    } finally {
     if (jjtc000) {
       jjtree.closeNodeScope(jjtn000, true);
     }
    }
    throw new Error("Missing return statement in function");
  }

// TODO: Support f�r inverse Rollen
  final public Concept Concept() throws ParseException {
 /*@bgen(jjtree) Concept */
        SimpleNode jjtn000 = new SimpleNode(JJTCONCEPT);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);Concept c,c1,c2;
        AtomicConcept ac;
        AtomicRole ar;
        String s;
        int i;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TOP:
        Top();
            jjtree.closeNodeScope(jjtn000, true);
            jjtc000 = false;
           {if (true) return new Top();}
        break;
      case BOTTOM:
        Bottom();
               jjtree.closeNodeScope(jjtn000, true);
               jjtc000 = false;
              {if (true) return new Bottom();}
        break;
      case ID:
      case STRING:
        ac = AtomicConcept();
                           jjtree.closeNodeScope(jjtn000, true);
                           jjtc000 = false;
                          {if (true) return ac;}
        break;
      default:
        jj_la1[10] = jj_gen;
        if (jj_2_11(2147483647)) {
          jj_consume_token(29);
          c1 = Concept();
          And();
          c2 = Concept();
          jj_consume_token(30);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
         {if (true) return new Conjunction(c1,c2);}
        } else if (jj_2_12(2147483647)) {
          jj_consume_token(29);
          c1 = Concept();
          Or();
          c2 = Concept();
          jj_consume_token(30);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
         {if (true) return new Disjunction(c1,c2);}
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case EXISTS:
            Exists();
            ar = AtomicRole();
            jj_consume_token(COMMAND_END);
            c = Concept();
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
         {if (true) return new Exists(ar,c);}
            break;
          case ALL:
            All();
            ar = AtomicRole();
            jj_consume_token(COMMAND_END);
            c = Concept();
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
         {if (true) return new All(ar,c);}
            break;
          case NOT:
            Not();
            c = Concept();
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
         {if (true) return new Negation(c);}
            break;
          case GE:
            GE();
            i = Integer();
            ar = AtomicRole();
            jj_consume_token(COMMAND_END);
            c = Concept();
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
         {if (true) return new GreaterEqual(i,ar,c);}
            break;
          case LE:
            LE();
            i = Integer();
            ar = AtomicRole();
            jj_consume_token(COMMAND_END);
            c = Concept();
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
         {if (true) return new LessEqual(i,ar,c);}
            break;
          default:
            jj_la1[11] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public void Or() throws ParseException {
             /*@bgen(jjtree) Or */
  SimpleNode jjtn000 = new SimpleNode(JJTOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(OR);
    } finally {
                   if (jjtc000) {
                     jjtree.closeNodeScope(jjtn000, true);
                   }
    }
  }

  final public void And() throws ParseException {
              /*@bgen(jjtree) And */
  SimpleNode jjtn000 = new SimpleNode(JJTAND);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(AND);
    } finally {
                    if (jjtc000) {
                      jjtree.closeNodeScope(jjtn000, true);
                    }
    }
  }

  final public void Top() throws ParseException {
              /*@bgen(jjtree) Top */
  SimpleNode jjtn000 = new SimpleNode(JJTTOP);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(TOP);
    } finally {
                    if (jjtc000) {
                      jjtree.closeNodeScope(jjtn000, true);
                    }
    }
  }

  final public void Bottom() throws ParseException {
                 /*@bgen(jjtree) Bottom */
  SimpleNode jjtn000 = new SimpleNode(JJTBOTTOM);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(BOTTOM);
    } finally {
                       if (jjtc000) {
                         jjtree.closeNodeScope(jjtn000, true);
                       }
    }
  }

  final public void Exists() throws ParseException {
                 /*@bgen(jjtree) Exists */
  SimpleNode jjtn000 = new SimpleNode(JJTEXISTS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(EXISTS);
    } finally {
                       if (jjtc000) {
                         jjtree.closeNodeScope(jjtn000, true);
                       }
    }
  }

  final public void All() throws ParseException {
              /*@bgen(jjtree) All */
  SimpleNode jjtn000 = new SimpleNode(JJTALL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ALL);
    } finally {
                    if (jjtc000) {
                      jjtree.closeNodeScope(jjtn000, true);
                    }
    }
  }

  final public void Not() throws ParseException {
              /*@bgen(jjtree) Not */
  SimpleNode jjtn000 = new SimpleNode(JJTNOT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(NOT);
    } finally {
                    if (jjtc000) {
                      jjtree.closeNodeScope(jjtn000, true);
                    }
    }
  }

  final public void GE() throws ParseException {
             /*@bgen(jjtree) GE */
  SimpleNode jjtn000 = new SimpleNode(JJTGE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(GE);
    } finally {
                   if (jjtc000) {
                     jjtree.closeNodeScope(jjtn000, true);
                   }
    }
  }

  final public void LE() throws ParseException {
             /*@bgen(jjtree) LE */
  SimpleNode jjtn000 = new SimpleNode(JJTLE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(LE);
    } finally {
                   if (jjtc000) {
                     jjtree.closeNodeScope(jjtn000, true);
                   }
    }
  }

  final public AtomicConcept AtomicConcept() throws ParseException {
 /*@bgen(jjtree) AtomicConcept */
        SimpleNode jjtn000 = new SimpleNode(JJTATOMICCONCEPT);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);String name;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ID:
        name = Id();
        break;
      case STRING:
        name = String();
        break;
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
                {if (true) return new AtomicConcept(getInternalURI(name));}
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
    throw new Error("Missing return statement in function");
  }

  final public AtomicRole AtomicRole() throws ParseException {
 /*@bgen(jjtree) AtomicRole */
        SimpleNode jjtn000 = new SimpleNode(JJTATOMICROLE);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);String name;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ID:
        name = Id();
        break;
      case STRING:
        name = String();
        break;
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
                {if (true) return new AtomicRole(getInternalURI(name));}
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
    throw new Error("Missing return statement in function");
  }

  final public Individual Individual() throws ParseException {
 /*@bgen(jjtree) Individual */
        SimpleNode jjtn000 = new SimpleNode(JJTINDIVIDUAL);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);String name;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ID:
        name = Id();
        break;
      case STRING:
        name = String();
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
                {if (true) return new Individual(getInternalURI(name));}
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
    throw new Error("Missing return statement in function");
  }

  final public String Id() throws ParseException {
 /*@bgen(jjtree) Id */
  SimpleNode jjtn000 = new SimpleNode(JJTID);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(ID);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    // jjtThis.setId(t.image);
    {if (true) return t.image;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public double Double() throws ParseException {
 /*@bgen(jjtree) Double */
  SimpleNode jjtn000 = new SimpleNode(JJTDOUBLE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(DOUBLE);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return new Double(t.image);}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public int Integer() throws ParseException {
 /*@bgen(jjtree) Integer */
  SimpleNode jjtn000 = new SimpleNode(JJTINTEGER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(NUMBER);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    // jjtThis.setId(t.image);
    // muss noch in Integer umgewandelt werden
    {if (true) return new Integer(t.image);}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public String String() throws ParseException {
 /*@bgen(jjtree) String */
  SimpleNode jjtn000 = new SimpleNode(JJTSTRING);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
  String s;
    try {
      t = jj_consume_token(STRING);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    // jjtThis.setId(t.image);
    // es werden sofort die Anfuehrungszeichen abgeschnitten
    s = t.image;
    s = s.substring(1, s.length() - 1);
    {if (true) return s;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  final private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  final private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  final private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  final private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  final private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  final private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  final private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  final private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  final private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  final private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  final private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  final private boolean jj_3R_32() {
    if (jj_3R_47()) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(COMMAND_END)) return true;
    if (jj_3R_14()) return true;
    return false;
  }

  final private boolean jj_3_10() {
    if (jj_scan_token(26)) return true;
    if (jj_scan_token(27)) return true;
    return false;
  }

  final private boolean jj_3R_26() {
    if (jj_3R_4()) return true;
    return false;
  }

  final private boolean jj_3_9() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_18()) {
    jj_scanpos = xsp;
    if (jj_3R_19()) return true;
    }
    if (jj_scan_token(28)) return true;
    return false;
  }

  final private boolean jj_3R_31() {
    if (jj_scan_token(29)) return true;
    if (jj_3R_14()) return true;
    if (jj_3R_21()) return true;
    if (jj_3R_14()) return true;
    if (jj_scan_token(30)) return true;
    return false;
  }

  final private boolean jj_3R_30() {
    if (jj_scan_token(29)) return true;
    if (jj_3R_14()) return true;
    if (jj_3R_20()) return true;
    if (jj_3R_14()) return true;
    if (jj_scan_token(30)) return true;
    return false;
  }

  final private boolean jj_3R_8() {
    if (jj_3R_23()) return true;
    return false;
  }

  final private boolean jj_3R_22() {
    if (jj_scan_token(NUMBER)) return true;
    return false;
  }

  final private boolean jj_3R_29() {
    if (jj_3R_46()) return true;
    return false;
  }

  final private boolean jj_3R_28() {
    if (jj_3R_45()) return true;
    return false;
  }

  final private boolean jj_3R_25() {
    if (jj_3R_12()) return true;
    return false;
  }

  final private boolean jj_3R_27() {
    if (jj_3R_44()) return true;
    return false;
  }

  final private boolean jj_3R_14() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_27()) {
    jj_scanpos = xsp;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) {
    jj_scanpos = xsp;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) {
    jj_scanpos = xsp;
    if (jj_3R_32()) {
    jj_scanpos = xsp;
    if (jj_3R_33()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_7() {
    if (jj_3R_22()) return true;
    return false;
  }

  final private boolean jj_3R_23() {
    if (jj_scan_token(DOUBLE)) return true;
    return false;
  }

  final private boolean jj_3R_38() {
    if (jj_3R_12()) return true;
    return false;
  }

  final private boolean jj_3R_6() {
    if (jj_3R_4()) return true;
    return false;
  }

  final private boolean jj_3_8() {
    if (jj_3R_14()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(31)) {
    jj_scanpos = xsp;
    if (jj_scan_token(32)) return true;
    }
    return false;
  }

  final private boolean jj_3R_43() {
    if (jj_3R_4()) return true;
    return false;
  }

  final private boolean jj_3_7() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(25)) return true;
    return false;
  }

  final private boolean jj_3R_13() {
    if (jj_scan_token(28)) return true;
    if (jj_3R_12()) return true;
    return false;
  }

  final private boolean jj_3R_4() {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  final private boolean jj_3R_41() {
    if (jj_3R_12()) return true;
    return false;
  }

  final private boolean jj_3R_37() {
    if (jj_3R_4()) return true;
    return false;
  }

  final private boolean jj_3R_15() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_37()) {
    jj_scanpos = xsp;
    if (jj_3R_38()) return true;
    }
    return false;
  }

  final private boolean jj_3R_42() {
    if (jj_3R_12()) return true;
    return false;
  }

  final private boolean jj_3R_16() {
    if (jj_3R_39()) return true;
    return false;
  }

  final private boolean jj_3R_24() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) return true;
    }
    if (jj_scan_token(28)) return true;
    return false;
  }

  final private boolean jj_3_6() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_16()) jj_scanpos = xsp;
    if (jj_3R_17()) return true;
    if (jj_scan_token(29)) return true;
    if (jj_3R_15()) return true;
    if (jj_scan_token(28)) return true;
    return false;
  }

  final private boolean jj_3R_5() {
    if (jj_scan_token(COMMAND_END)) return true;
    if (jj_3R_4()) return true;
    return false;
  }

  final private boolean jj_3R_52() {
    if (jj_3R_12()) return true;
    return false;
  }

  final private boolean jj_3_4() {
    if (jj_scan_token(NEG_EX)) return true;
    return false;
  }

  final private boolean jj_3R_40() {
    if (jj_3R_4()) return true;
    return false;
  }

  final private boolean jj_3_3() {
    if (jj_scan_token(POS_EX)) return true;
    return false;
  }

  final private boolean jj_3R_11() {
    if (jj_scan_token(26)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_24()) { jj_scanpos = xsp; break; }
    }
    xsp = jj_scanpos;
    if (jj_3R_25()) {
    jj_scanpos = xsp;
    if (jj_3R_26()) return true;
    }
    if (jj_scan_token(27)) return true;
    return false;
  }

  final private boolean jj_3R_17() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_3R_41()) return true;
    }
    return false;
  }

  final private boolean jj_3_2() {
    if (jj_3R_4()) return true;
    if (jj_scan_token(29)) return true;
    if (jj_3R_12()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_13()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(30)) return true;
    if (jj_scan_token(CONF_END)) return true;
    return false;
  }

  final private boolean jj_3_5() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(29)) return true;
    if (jj_3R_15()) return true;
    if (jj_scan_token(30)) return true;
    if (jj_scan_token(COMMAND_END)) return true;
    return false;
  }

  final private boolean jj_3_1() {
    if (jj_3R_4()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_5()) jj_scanpos = xsp;
    if (jj_scan_token(25)) return true;
    xsp = jj_scanpos;
    if (jj_3R_6()) {
    jj_scanpos = xsp;
    if (jj_3R_7()) {
    jj_scanpos = xsp;
    if (jj_3R_8()) {
    jj_scanpos = xsp;
    if (jj_3R_9()) {
    jj_scanpos = xsp;
    if (jj_3R_10()) {
    jj_scanpos = xsp;
    if (jj_3R_11()) return true;
    }
    }
    }
    }
    }
    if (jj_scan_token(CONF_END)) return true;
    return false;
  }

  final private boolean jj_3R_50() {
    if (jj_scan_token(LE)) return true;
    return false;
  }

  final private boolean jj_3R_47() {
    if (jj_scan_token(EXISTS)) return true;
    return false;
  }

  final private boolean jj_3R_49() {
    if (jj_scan_token(GE)) return true;
    return false;
  }

  final private boolean jj_3R_45() {
    if (jj_scan_token(BOTTOM)) return true;
    return false;
  }

  final private boolean jj_3R_39() {
    if (jj_scan_token(NOT)) return true;
    return false;
  }

  final private boolean jj_3R_10() {
    if (jj_scan_token(26)) return true;
    if (jj_scan_token(27)) return true;
    return false;
  }

  final private boolean jj_3R_51() {
    if (jj_3R_4()) return true;
    return false;
  }

  final private boolean jj_3R_48() {
    if (jj_scan_token(ALL)) return true;
    return false;
  }

  final private boolean jj_3R_46() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) return true;
    }
    return false;
  }

  final private boolean jj_3R_44() {
    if (jj_scan_token(TOP)) return true;
    return false;
  }

  final private boolean jj_3R_20() {
    if (jj_scan_token(AND)) return true;
    return false;
  }

  final private boolean jj_3R_21() {
    if (jj_scan_token(OR)) return true;
    return false;
  }

  final private boolean jj_3R_19() {
    if (jj_3R_4()) return true;
    return false;
  }

  final private boolean jj_3R_36() {
    if (jj_3R_50()) return true;
    if (jj_3R_22()) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(COMMAND_END)) return true;
    if (jj_3R_14()) return true;
    return false;
  }

  final private boolean jj_3R_18() {
    if (jj_3R_12()) return true;
    return false;
  }

  final private boolean jj_3R_35() {
    if (jj_3R_49()) return true;
    if (jj_3R_22()) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(COMMAND_END)) return true;
    if (jj_3R_14()) return true;
    return false;
  }

  final private boolean jj_3R_34() {
    if (jj_3R_39()) return true;
    if (jj_3R_14()) return true;
    return false;
  }

  final private boolean jj_3_12() {
    if (jj_scan_token(29)) return true;
    if (jj_3R_14()) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  final private boolean jj_3R_12() {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  final private boolean jj_3R_33() {
    if (jj_3R_48()) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(COMMAND_END)) return true;
    if (jj_3R_14()) return true;
    return false;
  }

  final private boolean jj_3R_9() {
    if (jj_3R_12()) return true;
    return false;
  }

  final private boolean jj_3_11() {
    if (jj_scan_token(29)) return true;
    if (jj_3R_14()) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  public DLLearnerTokenManager token_source;
  SimpleCharStream jj_input_stream;
  public Token token, jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  public boolean lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[15];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_0();
      jj_la1_1();
   }
   private static void jj_la1_0() {
      jj_la1_0 = new int[] {0x21f99c00,0x0,0x100,0x1001000,0x1001000,0x1007000,0x4000000,0x10000000,0x200000,0x80000000,0x1019000,0xf80000,0x1001000,0x1001000,0x1001000,};
   }
   private static void jj_la1_1() {
      jj_la1_1 = new int[] {0x3e,0x3e,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x41,0x0,0x0,0x0,0x0,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[12];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  public DLLearner(java.io.InputStream stream) {
     this(stream, null);
  }
  public DLLearner(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new DLLearnerTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public DLLearner(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new DLLearnerTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public DLLearner(DLLearnerTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(DLLearnerTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  final private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  final private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }

  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  final public Token getToken(int index) {
    Token t = lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  final private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.Vector<int[]> jj_expentries = new java.util.Vector<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Enumeration e = jj_expentries.elements(); e.hasMoreElements();) {
        int[] oldentry = (int[])(e.nextElement());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.addElement(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  public ParseException generateParseException() {
    jj_expentries.removeAllElements();
    boolean[] la1tokens = new boolean[39];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 15; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 39; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.addElement(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.elementAt(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  final public void enable_tracing() {
  }

  final public void disable_tracing() {
  }

  final private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 12; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  final private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
