/* Generated By:JJTree: Do not edit this line. ./KBParserTreeConstants.java */

package org.dllearner.parser;

public @SuppressWarnings("all") interface KBParserTreeConstants
{
  public int JJTKB = 0;
  public int JJTABOXCONCEPT = 1;
  public int JJTABOXROLE = 2;
  public int JJTTRANSITIVE = 3;
  public int JJTFUNCTIONAL = 4;
  public int JJTSYMMETRIC = 5;
  public int JJTINVERSE = 6;
  public int JJTSUBROLE = 7;
  public int JJTTBOXEQUIV = 8;
  public int JJTTBOXSUB = 9;
  public int JJTCONCEPT = 10;
  public int JJTOR = 11;
  public int JJTAND = 12;
  public int JJTTOP = 13;
  public int JJTBOTTOM = 14;
  public int JJTEXISTS = 15;
  public int JJTALL = 16;
  public int JJTNOT = 17;
  public int JJTGE = 18;
  public int JJTLE = 19;
  public int JJTATOMICCONCEPT = 20;
  public int JJTATOMICROLE = 21;
  public int JJTINDIVIDUAL = 22;
  public int JJTID = 23;
  public int JJTDOUBLE = 24;
  public int JJTINTEGER = 25;
  public int JJTSTRING = 26;


  public String[] jjtNodeName = {
    "KB",
    "ABoxConcept",
    "ABoxRole",
    "Transitive",
    "Functional",
    "Symmetric",
    "Inverse",
    "Subrole",
    "TBoxEquiv",
    "TBoxSub",
    "Concept",
    "Or",
    "And",
    "Top",
    "Bottom",
    "Exists",
    "All",
    "Not",
    "GE",
    "LE",
    "AtomicConcept",
    "AtomicRole",
    "Individual",
    "Id",
    "Double",
    "Integer",
    "String",
  };
}
