/* Generated By:JavaCC: Do not edit this line. PrologParserConstants.java */
package org.dllearner.parser;

public @SuppressWarnings("all") interface PrologParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int NOT = 7;
  int NUMBER = 8;
  int DIGIT = 9;
  int STRINGCONSTANT = 10;
  int VAR = 11;
  int IDENTIFIER = 12;
  int OPERATOR = 13;
  int ANYCHAR = 14;
  int LOCASE = 15;
  int HICASE = 16;
  int SPECIALCHAR = 17;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"not\"",
    "<NUMBER>",
    "<DIGIT>",
    "<STRINGCONSTANT>",
    "<VAR>",
    "<IDENTIFIER>",
    "<OPERATOR>",
    "<ANYCHAR>",
    "<LOCASE>",
    "<HICASE>",
    "<SPECIALCHAR>",
    "\":-\"",
    "\".\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[]\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
  };

}
