/* Generated By:JavaCC: Do not edit this line. LTAGTreeParserConstants.java */
package org.dllearner.algorithm.tbsl.ltag.reader;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LTAGTreeParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WORD = 11;
  /** RegularExpression Id. */
  int CATEGORY = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"*\"",
    "\"^\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\"\\\'\"",
    "<WORD>",
    "<CATEGORY>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
