has_property(d1,salmonella,p).
has_property(d1,salmonella_n,p).
has_property(d1,cytogen_ca,p).
has_property(d1,cytogen_sce,p).
has_property(d2,salmonella,p).
has_property(d2,cytogen_ca,n).
has_property(d2,cytogen_sce,p).
has_property(d3,salmonella,p).
has_property(d3,cytogen_ca,p).
has_property(d3,cytogen_sce,p).
has_property(d4,salmonella_n,p).
has_property(d5,salmonella,p).
has_property(d5,salmonella_n,p).
has_property(d5,cytogen_ca,p).
has_property(d5,cytogen_sce,p).
has_property(d6,salmonella,p).
has_property(d6,salmonella_n,p).
has_property(d6,cytogen_ca,p).
has_property(d6,cytogen_sce,p).
has_property(d7,salmonella,p).
has_property(d7,cytogen_ca,n).
has_property(d8,salmonella,p).
has_property(d8,mouse_lymph,p).
has_property(d8,cytogen_ca,n).
has_property(d8,cytogen_sce,p).
has_property(d8,chromaberr,n).
has_property(d8,chromex,p).
has_property(d9,salmonella,p).
has_property(d9,salmonella_n,p).
has_property(d9,cytogen_ca,p).
has_property(d9,cytogen_sce,p).
has_property(d10,salmonella,p).
has_property(d10,salmonella_n,p).
has_property(d10,cytogen_ca,p).
has_property(d10,cytogen_sce,p).
has_property(d11,salmonella,p).
has_property(d11,salmonella_n,p).
has_property(d11,mouse_lymph,p).
has_property(d11,cytogen_ca,p).
has_property(d11,cytogen_sce,p).
has_property(d12,salmonella,p).
has_property(d12,cytogen_ca,p).
has_property(d12,cytogen_sce,p).
has_property(d12,micronuc_m,n).
has_property(d12,micronuc_f,n).
has_property(d13,salmonella,p).
has_property(d13,mouse_lymph,p).
has_property(d13,drosophila_slrl,p).
has_property(d13,drosophila_rt,n).
has_property(d13,cytogen_ca,p).
has_property(d13,cytogen_sce,p).
has_property(d13,chromaberr,p).
has_property(d14,salmonella,p).
has_property(d14,salmonella_n,p).
has_property(d14,cytogen_ca,p).
has_property(d14,cytogen_sce,p).
has_property(d15,salmonella,p).
has_property(d15,mouse_lymph,p).
has_property(d15,drosophila_slrl,p).
has_property(d15,drosophila_rt,n).
has_property(d15,cytogen_ca,p).
has_property(d15,cytogen_sce,p).
has_property(d16,salmonella,p).
has_property(d16,cytogen_ca,p).
has_property(d16,cytogen_sce,p).
has_property(d17,salmonella,p).
has_property(d17,salmonella_n,p).
has_property(d17,cytogen_ca,p).
has_property(d17,cytogen_sce,p).
has_property(d18,salmonella,p).
has_property(d18,cytogen_ca,n).
has_property(d18,cytogen_sce,p).
has_property(d19,salmonella,p).
has_property(d19,salmonella_n,p).
has_property(d19,cytogen_ca,p).
has_property(d19,cytogen_sce,p).
has_property(d20,salmonella,p).
has_property(d20,cytogen_ca,n).
has_property(d20,cytogen_sce,p).
has_property(d21,salmonella_n,p).
has_property(d21,mouse_lymph,p).
has_property(d21,cytogen_ca,n).
has_property(d21,cytogen_sce,n).
has_property(d22,salmonella,p).
has_property(d22,mouse_lymph,p).
has_property(d22,cytogen_ca,p).
has_property(d22,cytogen_sce,p).
has_property(d23_1,salmonella,p).
has_property(d23_1,mouse_lymph,p).
has_property(d23_1,cytogen_ca,p).
has_property(d23_1,cytogen_sce,p).
has_property(d23_1,chromaberr,p).
has_property(d23_1,chromex,n).
has_property(d23_2,mouse_lymph,p).
has_property(d23_2,cytogen_ca,p).
has_property(d23_2,cytogen_sce,p).
has_property(d25,salmonella,n).
has_property(d25,cytogen_sce,p).
has_property(d25,chromex,p).
has_property(d26,salmonella,p).
has_property(d26,cytogen_ca,p).
has_property(d26,cytogen_sce,p).
has_property(d27,salmonella,p).
has_property(d27,salmonella,p).
has_property(d27,mouse_lymph,p).
has_property(d27,cytogen_ca,p).
has_property(d27,cytogen_sce,p).
has_property(d28,salmonella,p).
has_property(d28,mouse_lymph,p).
has_property(d28,cytogen_ca,p).
has_property(d28,cytogen_sce,p).
has_property(d29,salmonella,p).
has_property(d29,drosophila_slrl,p).
has_property(d29,drosophila_rt,p).
has_property(d29,cytogen_ca,n).
has_property(d29,cytogen_sce,p).
has_property(d29,chromaberr,n).
has_property(d31,mouse_lymph,p).
has_property(d32,salmonella,p).
has_property(d32,drosophila_slrl,p).
has_property(d32,drosophila_rt,n).
has_property(d32,cytogen_ca,p).
has_property(d32,cytogen_sce,p).
has_property(d33,salmonella_n,n).
has_property(d34,salmonella,p).
has_property(d34,cytogen_sce,p).
has_property(d35,salmonella,n).
has_property(d35,mouse_lymph,n).
has_property(d35,cytogen_ca,n).
has_property(d35,cytogen_sce,n).
has_property(d36,salmonella,p).
has_property(d36,mouse_lymph,n).
has_property(d36,cytogen_ca,n).
has_property(d36,cytogen_sce,n).
has_property(d36,chromaberr,n).
has_property(d36,chromex,p).
has_property(d37,salmonella,p).
has_property(d37,salmonella_n,p).
has_property(d37,cytogen_ca,p).
has_property(d37,cytogen_sce,p).
has_property(d38,salmonella,p).
has_property(d38,salmonella_n,p).
has_property(d38,mouse_lymph,p).
has_property(d38,drosophila_slrl,p).
has_property(d38,drosophila_rt,n).
has_property(d38,cytogen_ca,n).
has_property(d38,cytogen_sce,p).
has_property(d39,salmonella,p).
has_property(d39,salmonella_n,p).
has_property(d39,cytogen_ca,p).
has_property(d39,cytogen_sce,p).
has_property(d40,salmonella,n).
has_property(d40,salmonella_n,n).
has_property(d40,mouse_lymph,n).
has_property(d40,cytogen_ca,p).
has_property(d41,salmonella,p).
has_property(d41,cytogen_ca,n).
has_property(d41,cytogen_sce,n).
has_property(d42,salmonella,n).
has_property(d42,mouse_lymph,p).
has_property(d42,cytogen_ca,p).
has_property(d42,cytogen_sce,p).
has_property(d43,salmonella,p).
has_property(d43,mouse_lymph,p).
has_property(d43,cytogen_ca,p).
has_property(d43,cytogen_sce,p).
has_property(d44,salmonella,p).
has_property(d44,salmonella_n,n).
has_property(d44,cytogen_ca,p).
has_property(d44,cytogen_sce,p).
has_property(d45,salmonella,p).
has_property(d45,mouse_lymph,p).
has_property(d45,cytogen_ca,p).
has_property(d45,cytogen_sce,p).
has_property(d45,chromaberr,p).
has_property(d45,chromex,p).
has_property(d46,salmonella,p).
has_property(d46,salmonella_n,p).
has_property(d46,cytogen_ca,p).
has_property(d46,cytogen_sce,p).
has_property(d47,salmonella,p).
has_property(d47,mouse_lymph,p).
has_property(d47,cytogen_ca,n).
has_property(d47,cytogen_sce,p).
has_property(d47,chromaberr,n).
has_property(d47,chromex,p).
has_property(d48,salmonella,p).
has_property(d48,salmonella_n,p).
has_property(d48,cytogen_ca,n).
has_property(d48,cytogen_sce,p).
has_property(d49,salmonella,p).
has_property(d49,salmonella_n,p).
has_property(d49,mouse_lymph,p).
has_property(d49,cytogen_ca,p).
has_property(d49,cytogen_sce,p).
has_property(d50,salmonella,p).
has_property(d50,salmonella_n,p).
has_property(d50,mouse_lymph,p).
has_property(d50,cytogen_ca,p).
has_property(d50,cytogen_sce,p).
has_property(d51,salmonella,p).
has_property(d51,salmonella_n,p).
has_property(d51,mouse_lymph,p).
has_property(d51,cytogen_ca,p).
has_property(d51,cytogen_sce,p).
has_property(d52,salmonella,p).
has_property(d52,mouse_lymph,p).
has_property(d52,cytogen_ca,p).
has_property(d52,cytogen_sce,n).
has_property(d52,chromaberr,n).
has_property(d53,salmonella,p).
has_property(d53,cytogen_ca,p).
has_property(d53,cytogen_sce,p).
has_property(d54,salmonella,p).
has_property(d54,cytogen_ca,n).
has_property(d54,cytogen_sce,n).
has_property(d55,salmonella,p).
has_property(d55,salmonella_n,p).
has_property(d55,mouse_lymph,p).
has_property(d55,cytogen_ca,p).
has_property(d55,cytogen_sce,p).
has_property(d56,salmonella,p).
has_property(d56,mouse_lymph,p).
has_property(d56,cytogen_ca,p).
has_property(d56,cytogen_sce,p).
has_property(d57,salmonella,p).
has_property(d57,mouse_lymph,p).
has_property(d57,cytogen_ca,p).
has_property(d57,cytogen_sce,p).
has_property(d58,salmonella,p).
has_property(d58,cytogen_ca,p).
has_property(d58,cytogen_sce,p).
has_property(d59,salmonella_n,p).
has_property(d59,mouse_lymph,p).
has_property(d60,salmonella,n).
has_property(d60,salmonella_n,p).
has_property(d60,mouse_lymph,p).
has_property(d60,cytogen_ca,p).
has_property(d60,cytogen_sce,p).
has_property(d61,salmonella,p).
has_property(d61,cytogen_ca,n).
has_property(d61,cytogen_sce,p).
has_property(d62,salmonella_n,p).
has_property(d63,salmonella,p).
has_property(d63,mouse_lymph,p).
has_property(d63,cytogen_ca,p).
has_property(d63,cytogen_sce,p).
has_property(d64,salmonella,n).
has_property(d64,mouse_lymph,p).
has_property(d64,cytogen_ca,n).
has_property(d64,cytogen_sce,p).
has_property(d65,salmonella,n).
has_property(d65,mouse_lymph,p).
has_property(d65,cytogen_ca,n).
has_property(d65,cytogen_sce,n).
has_property(d66,salmonella,n).
has_property(d66,mouse_lymph,p).
has_property(d66,cytogen_ca,p).
has_property(d66,cytogen_sce,p).
has_property(d67,salmonella,p).
has_property(d67,salmonella_n,p).
has_property(d67,cytogen_ca,p).
has_property(d67,cytogen_sce,p).
has_property(d68,salmonella,p).
has_property(d68,mouse_lymph,p).
has_property(d68,cytogen_ca,p).
has_property(d68,cytogen_sce,p).
has_property(d69,salmonella,n).
has_property(d69,cytogen_sce,p).
has_property(d70,salmonella,p).
has_property(d70,salmonella_n,p).
has_property(d71,salmonella,p).
has_property(d71,cytogen_ca,n).
has_property(d71,cytogen_sce,p).
has_property(d72,salmonella,p).
has_property(d72,mouse_lymph,p).
has_property(d72,cytogen_ca,p).
has_property(d72,cytogen_sce,p).
has_property(d73,salmonella,p).
has_property(d73,salmonella_n,p).
has_property(d73,mouse_lymph,p).
has_property(d73,cytogen_ca,n).
has_property(d73,cytogen_sce,p).
has_property(d74,salmonella,n).
has_property(d74,mouse_lymph,p).
has_property(d74,cytogen_ca,p).
has_property(d74,cytogen_sce,p).
has_property(d75,salmonella,p).
has_property(d75,mouse_lymph,p).
has_property(d75,cytogen_ca,p).
has_property(d75,cytogen_sce,p).
has_property(d75,chromaberr,n).
has_property(d75,chromex,n).
has_property(d76,salmonella,n).
has_property(d76,mouse_lymph,p).
has_property(d76,cytogen_ca,p).
has_property(d76,cytogen_sce,n).
has_property(d76,chromaberr,n).
has_property(d76,chromex,p).
has_property(d77,salmonella,n).
has_property(d77,salmonella_reduc,n).
has_property(d77,mouse_lymph,n).
has_property(d77,cytogen_ca,n).
has_property(d78,salmonella,p).
has_property(d78,mouse_lymph,p).
has_property(d78,cytogen_ca,n).
has_property(d78,cytogen_sce,p).
has_property(d78,chromaberr,n).
has_property(d78,chromex,p).
has_property(d79,salmonella,p).
has_property(d79,mouse_lymph,n).
has_property(d79,cytogen_ca,p).
has_property(d79,cytogen_sce,p).
has_property(d80,salmonella,p).
has_property(d80,salmonella_n,p).
has_property(d80,cytogen_ca,p).
has_property(d80,cytogen_sce,n).
has_property(d81,salmonella,p).
has_property(d81,salmonella_n,p).
has_property(d81,mouse_lymph,p).
has_property(d81,cytogen_ca,p).
has_property(d81,cytogen_sce,p).
has_property(d82,salmonella,n).
has_property(d82,salmonella_n,n).
has_property(d82,mouse_lymph,p).
has_property(d82,cytogen_ca,n).
has_property(d82,cytogen_sce,p).
has_property(d82,chromaberr,n).
has_property(d83,salmonella,p).
has_property(d83,salmonella_n,p).
has_property(d83,mouse_lymph,p).
has_property(d83,cytogen_ca,p).
has_property(d83,cytogen_sce,p).
has_property(d86,mouse_lymph,n).
has_property(d86,chromaberr,n).
has_property(d87,salmonella,n).
has_property(d87,mouse_lymph,n).
has_property(d87,cytogen_ca,n).
has_property(d87,cytogen_sce,n).
has_property(d87,chromaberr,n).
has_property(d89,salmonella,n).
has_property(d89,mouse_lymph,p).
has_property(d89,cytogen_sce,p).
has_property(d90,salmonella,n).
has_property(d90,cytogen_ca,n).
has_property(d90,cytogen_sce,n).
has_property(d90,micronuc_m,n).
has_property(d90,micronuc_f,n).
has_property(d90,chromaberr,n).
has_property(d91,salmonella,n).
has_property(d91,cytogen_ca,n).
has_property(d91,cytogen_sce,n).
has_property(d91,chromaberr,n).
has_property(d92,salmonella,n).
has_property(d92,cytogen_ca,n).
has_property(d92,cytogen_sce,p).
has_property(d93,salmonella,n).
has_property(d93,cytogen_ca,p).
has_property(d93,cytogen_sce,p).
has_property(d94,salmonella,n).
has_property(d94,cytogen_ca,p).
has_property(d94,cytogen_sce,p).
has_property(d95,salmonella,n).
has_property(d95,mouse_lymph,n).
has_property(d95,cytogen_ca,p).
has_property(d95,cytogen_sce,p).
has_property(d95,chromaberr,n).
has_property(d96,salmonella,p).
has_property(d96,mouse_lymph,p).
has_property(d97,salmonella,n).
has_property(d97,mouse_lymph,n).
has_property(d97,cytogen_ca,n).
has_property(d97,cytogen_sce,n).
has_property(d98,salmonella,n).
has_property(d98,mouse_lymph,p).
has_property(d98,cytogen_ca,p).
has_property(d98,cytogen_sce,p).
has_property(d99,salmonella,n).
has_property(d99,mouse_lymph,n).
has_property(d99,cytogen_ca,n).
has_property(d99,cytogen_sce,n).
has_property(d100,salmonella,n).
has_property(d100,mouse_lymph,p).
has_property(d100,drosophila_slrl,p).
has_property(d100,drosophila_rt,n).
has_property(d100,cytogen_ca,n).
has_property(d100,cytogen_sce,p).
has_property(d101,salmonella,n).
has_property(d101,mouse_lymph,p).
has_property(d101,cytogen_ca,n).
has_property(d101,cytogen_sce,p).
has_property(d102,salmonella,n).
has_property(d102,mouse_lymph,p).
has_property(d102,cytogen_ca,n).
has_property(d102,cytogen_sce,p).
has_property(d102,chromaberr,n).
has_property(d103,salmonella,n).
has_property(d103,mouse_lymph,n).
has_property(d103,cytogen_ca,n).
has_property(d103,cytogen_sce,p).
has_property(d103,chromaberr,p).
has_property(d104,salmonella,n).
has_property(d104,mouse_lymph,n).
has_property(d104,cytogen_ca,n).
has_property(d104,cytogen_sce,p).
has_property(d105,salmonella,n).
has_property(d105,mouse_lymph,p).
has_property(d105,cytogen_ca,n).
has_property(d105,cytogen_sce,p).
has_property(d105,chromaberr,n).
has_property(d106,salmonella,n).
has_property(d108,salmonella,n).
has_property(d108,mouse_lymph,p).
has_property(d108,cytogen_ca,n).
has_property(d108,cytogen_sce,n).
has_property(d109,salmonella,n).
has_property(d109,mouse_lymph,p).
has_property(d109,cytogen_ca,p).
has_property(d109,cytogen_sce,p).
has_property(d110,salmonella,n).
has_property(d110,mouse_lymph,p).
has_property(d110,cytogen_ca,n).
has_property(d110,cytogen_sce,p).
has_property(d110,chromex,n).
has_property(d111,salmonella,n).
has_property(d112,salmonella,n).
has_property(d112,mouse_lymph,p).
has_property(d112,cytogen_ca,n).
has_property(d112,cytogen_sce,p).
has_property(d113,salmonella,p).
has_property(d113,cytogen_ca,n).
has_property(d113,cytogen_sce,p).
has_property(d114,salmonella,n).
has_property(d114,cytogen_ca,p).
has_property(d114,cytogen_sce,p).
has_property(d115,salmonella,n).
has_property(d115,mouse_lymph,n).
has_property(d115,cytogen_ca,p).
has_property(d115,cytogen_sce,p).
has_property(d115,chromaberr,p).
has_property(d115,chromex,p).
has_property(d116,salmonella,n).
has_property(d116,cytogen_ca,n).
has_property(d116,cytogen_sce,n).
has_property(d117,salmonella,n).
has_property(d117,mouse_lymph,p).
has_property(d117,cytogen_ca,n).
has_property(d117,cytogen_sce,p).
has_property(d118,salmonella,n).
has_property(d118,salmonella_n,n).
has_property(d118,mouse_lymph,p).
has_property(d118,cytogen_ca,n).
has_property(d118,cytogen_sce,p).
has_property(d119,salmonella,n).
has_property(d119,mouse_lymph,n).
has_property(d119,cytogen_ca,n).
has_property(d119,cytogen_sce,n).
has_property(d120,salmonella,n).
has_property(d120,mouse_lymph,p).
has_property(d120,cytogen_ca,n).
has_property(d120,cytogen_sce,p).
has_property(d120,micronuc_m,n).
has_property(d120,micronuc_f,n).
has_property(d120,chromaberr,n).
has_property(d120,chromex,n).
has_property(d121,salmonella,n).
has_property(d121,mouse_lymph,n).
has_property(d121,cytogen_ca,n).
has_property(d121,cytogen_sce,n).
has_property(d122,salmonella,n).
has_property(d122,salmonella_n,n).
has_property(d122,mouse_lymph,p).
has_property(d122,cytogen_ca,n).
has_property(d122,cytogen_sce,p).
has_property(d123,salmonella,n).
has_property(d123,cytogen_ca,n).
has_property(d123,cytogen_sce,n).
has_property(d124,salmonella,n).
has_property(d124,mouse_lymph,n).
has_property(d124,cytogen_ca,n).
has_property(d124,cytogen_sce,p).
has_property(d125,salmonella,n).
has_property(d125,mouse_lymph,n).
has_property(d125,cytogen_ca,n).
has_property(d125,cytogen_sce,n).
has_property(d126,salmonella,n).
has_property(d126,cytogen_ca,n).
has_property(d126,cytogen_sce,n).
has_property(d127,salmonella,n).
has_property(d127,mouse_lymph,n).
has_property(d127,cytogen_ca,p).
has_property(d127,cytogen_sce,n).
has_property(d128,salmonella,p).
has_property(d128,cytogen_ca,n).
has_property(d128,cytogen_sce,p).
has_property(d129,salmonella,n).
has_property(d129,mouse_lymph,p).
has_property(d130,mouse_lymph,p).
has_property(d130,cytogen_ca,p).
has_property(d130,cytogen_sce,p).
has_property(d131,salmonella,n).
has_property(d131,salmonella_n,n).
has_property(d131,mouse_lymph,p).
has_property(d131,cytogen_sce,p).
has_property(d132,salmonella,n).
has_property(d132,mouse_lymph,n).
has_property(d132,cytogen_ca,p).
has_property(d132,cytogen_sce,p).
has_property(d133,salmonella,n).
has_property(d133,mouse_lymph,p).
has_property(d133,cytogen_ca,n).
has_property(d133,cytogen_sce,p).
has_property(d134,salmonella,n).
has_property(d134,mouse_lymph,n).
has_property(d134,cytogen_ca,n).
has_property(d134,cytogen_sce,p).
has_property(d134,chromex,p).
has_property(d135,salmonella,n).
has_property(d135,mouse_lymph,n).
has_property(d135,cytogen_ca,p).
has_property(d135,cytogen_sce,n).
has_property(d135,cytogen_ca,n).
has_property(d135,cytogen_sce,n).
has_property(d136,salmonella,n).
has_property(d136,cytogen_ca,n).
has_property(d136,cytogen_sce,n).
has_property(d137,salmonella,n).
has_property(d137,salmonella_n,n).
has_property(d137,mouse_lymph,n).
has_property(d137,cytogen_ca,n).
has_property(d137,cytogen_sce,n).
has_property(d137,chromaberr,p).
has_property(d137,chromex,n).
has_property(d138,salmonella,n).
has_property(d138,mouse_lymph,p).
has_property(d138,cytogen_ca,p).
has_property(d138,cytogen_sce,p).
has_property(d139,salmonella,n).
has_property(d139,mouse_lymph,n).
has_property(d139,cytogen_ca,n).
has_property(d139,cytogen_sce,p).
has_property(d139,chromaberr,n).
has_property(d140,salmonella,n).
has_property(d140,mouse_lymph,n).
has_property(d140,cytogen_ca,p).
has_property(d140,cytogen_sce,p).
has_property(d141,salmonella,n).
has_property(d141,mouse_lymph,p).
has_property(d141,cytogen_ca,n).
has_property(d141,cytogen_sce,n).
has_property(d141,micronuc_m,n).
has_property(d141,micronuc_f,n).
has_property(d141,chromaberr,n).
has_property(d141,chromex,n).
has_property(d142,mouse_lymph,p).
has_property(d142,cytogen_ca,p).
has_property(d143,salmonella,n).
has_property(d143,mouse_lymph,n).
has_property(d143,cytogen_ca,n).
has_property(d143,cytogen_sce,n).
has_property(d144,salmonella,n).
has_property(d144,mouse_lymph,n).
has_property(d144,cytogen_ca,p).
has_property(d144,chromaberr,n).
has_property(d144,chromex,n).
has_property(d145,salmonella,n).
has_property(d145,mouse_lymph,n).
has_property(d145,cytogen_ca,n).
has_property(d145,cytogen_sce,n).
has_property(d145,chromaberr,p).
has_property(d145,chromex,p).
has_property(d146,salmonella,n).
has_property(d146,mouse_lymph,p).
has_property(d146,cytogen_ca,n).
has_property(d146,cytogen_sce,n).
has_property(d147,salmonella,n).
has_property(d147,mouse_lymph,n).
has_property(d147,cytogen_ca,n).
has_property(d147,cytogen_sce,n).
has_property(d147,chromaberr,n).
has_property(d148,salmonella,n).
has_property(d148,mouse_lymph,p).
has_property(d148,cytogen_ca,p).
has_property(d148,cytogen_sce,n).
has_property(d149,salmonella,n).
has_property(d149,mouse_lymph,n).
has_property(d149,cytogen_ca,n).
has_property(d150,salmonella,n).
has_property(d150,mouse_lymph,n).
has_property(d150,cytogen_ca,n).
has_property(d150,cytogen_sce,n).
has_property(d151,salmonella,n).
has_property(d151,mouse_lymph,p).
has_property(d151,cytogen_ca,p).
has_property(d151,cytogen_sce,p).
has_property(d151,chromaberr,p).
has_property(d152,salmonella,n).
has_property(d152,mouse_lymph,n).
has_property(d152,cytogen_ca,n).
has_property(d152,cytogen_sce,n).
has_property(d153,salmonella,n).
has_property(d153,mouse_lymph,p).
has_property(d153,cytogen_ca,n).
has_property(d153,cytogen_sce,p).
has_property(d155,salmonella,n).
has_property(d155,mouse_lymph,p).
has_property(d155,cytogen_ca,n).
has_property(d156,salmonella,n).
has_property(d156,mouse_lymph,p).
has_property(d156,cytogen_ca,n).
has_property(d157,salmonella,n).
has_property(d157,mouse_lymph,n).
has_property(d157,cytogen_ca,p).
has_property(d157,cytogen_sce,n).
has_property(d158,salmonella,n).
has_property(d158,mouse_lymph,p).
has_property(d158,cytogen_ca,n).
has_property(d158,cytogen_sce,p).
has_property(d159,salmonella,n).
has_property(d159,salmonella_n,n).
has_property(d159,mouse_lymph,n).
has_property(d159,cytogen_ca,n).
has_property(d160,salmonella,p).
has_property(d160,cytogen_ca,n).
has_property(d160,cytogen_sce,p).
has_property(d160,chromaberr,p).
has_property(d160,chromex,p).
has_property(d161,salmonella,n).
has_property(d161,mouse_lymph,p).
has_property(d161,cytogen_ca,n).
has_property(d161,cytogen_sce,n).
has_property(d163,salmonella,n).
has_property(d163,salmonella_n,n).
has_property(d163,mouse_lymph,n).
has_property(d163,cytogen_ca,n).
has_property(d163,cytogen_sce,n).
has_property(d165,salmonella,n).
has_property(d165,mouse_lymph,p).
has_property(d165,cytogen_ca,n).
has_property(d166,salmonella,n).
has_property(d166,mouse_lymph,n).
has_property(d166,cytogen_ca,n).
has_property(d166,cytogen_sce,n).
has_property(d167,salmonella,n).
has_property(d167,mouse_lymph,n).
has_property(d167,cytogen_sce,p).
has_property(d168,salmonella,n).
has_property(d168,mouse_lymph,n).
has_property(d168,cytogen_ca,n).
has_property(d168,cytogen_sce,n).
has_property(d169,salmonella,n).
has_property(d169,mouse_lymph,p).
has_property(d169,cytogen_ca,p).
has_property(d169,cytogen_sce,p).
has_property(d170,salmonella,n).
has_property(d170,mouse_lymph,p).
has_property(d170,cytogen_ca,n).
has_property(d170,cytogen_sce,n).
has_property(d171,mouse_lymph,n).
has_property(d171,cytogen_ca,n).
has_property(d171,cytogen_sce,n).
has_property(d172,salmonella,n).
has_property(d172,salmonella_n,n).
has_property(d172,mouse_lymph,p).
has_property(d172,cytogen_ca,n).
has_property(d172,cytogen_sce,n).
has_property(d173,salmonella,n).
has_property(d173,salmonella_n,n).
has_property(d173,mouse_lymph,p).
has_property(d173,cytogen_ca,n).
has_property(d173,cytogen_sce,n).
has_property(d174,salmonella,n).
has_property(d174,mouse_lymph,n).
has_property(d174,cytogen_ca,n).
has_property(d174,cytogen_sce,n).
has_property(d176,salmonella,n).
has_property(d176,mouse_lymph,n).
has_property(d176,cytogen_ca,n).
has_property(d176,cytogen_sce,n).
has_property(d177,salmonella,n).
has_property(d177,mouse_lymph,p).
has_property(d177,cytogen_ca,n).
has_property(d177,cytogen_sce,n).
has_property(d178,salmonella,n).
has_property(d178,salmonella_n,n).
has_property(d178,mouse_lymph,n).
has_property(d178,cytogen_sce,n).
has_property(d178,chromaberr,n).
has_property(d179,salmonella,n).
has_property(d179,mouse_lymph,n).
has_property(d179,cytogen_ca,n).
has_property(d179,cytogen_sce,p).
has_property(d180,salmonella,n).
has_property(d180,cytogen_ca,n).
has_property(d180,cytogen_sce,n).
has_property(d181,salmonella,n).
has_property(d181,cytogen_ca,p).
has_property(d181,cytogen_sce,p).
has_property(d182,salmonella,n).
has_property(d182,mouse_lymph,p).
has_property(d182,cytogen_ca,n).
has_property(d183,salmonella,n).
has_property(d183,cytogen_ca,n).
has_property(d183,cytogen_sce,n).
has_property(d184,cytogen_ca,n).
has_property(d184,cytogen_sce,n).
has_property(d185,salmonella,n).
has_property(d185,cytogen_ca,n).
has_property(d185,cytogen_sce,n).
has_property(d186,salmonella,n).
has_property(d186,cytogen_ca,n).
has_property(d186,cytogen_sce,n).
has_property(d187,salmonella,n).
has_property(d187,mouse_lymph,p).
has_property(d187,cytogen_ca,n).
has_property(d187,cytogen_sce,p).
has_property(d188,salmonella,n).
has_property(d188,mouse_lymph,p).
has_property(d188,cytogen_ca,n).
has_property(d188,cytogen_sce,n).
has_property(d190,salmonella,n).
has_property(d190,cytogen_ca,n).
has_property(d190,cytogen_sce,n).
has_property(d191,salmonella,n).
has_property(d191,mouse_lymph,p).
has_property(d191,cytogen_ca,p).
has_property(d191,cytogen_sce,p).
has_property(d191,chromaberr,n).
has_property(d192,salmonella,n).
has_property(d192,salmonella_n,n).
has_property(d192,mouse_lymph,p).
has_property(d192,cytogen_ca,n).
has_property(d192,cytogen_sce,n).
has_property(d192,chromaberr,n).
has_property(d193,salmonella,n).
has_property(d193,mouse_lymph,n).
has_property(d193,cytogen_ca,n).
has_property(d193,cytogen_sce,p).
has_property(d195,salmonella,n).
has_property(d195,mouse_lymph,p).
has_property(d195,cytogen_ca,n).
has_property(d195,cytogen_sce,p).
has_property(d196,mouse_lymph,p).
has_property(d196,drosophila_slrl,p).
has_property(d196,drosophila_rt,n).
has_property(d196,cytogen_ca,p).
has_property(d196,cytogen_sce,p).
has_property(d196,chromaberr,n).
has_property(d197,salmonella,n).
has_property(d197,mouse_lymph,p).
has_property(d197,cytogen_ca,p).
has_property(d197,cytogen_sce,n).
has_property(d198,salmonella,n).
has_property(d198,mouse_lymph,p).
has_property(d198,cytogen_ca,n).
has_property(d198,cytogen_sce,n).
has_property(d199,salmonella,n).
has_property(d199,salmonella_n,n).
has_property(d199,mouse_lymph,p).
has_property(d199,cytogen_ca,n).
has_property(d199,cytogen_sce,p).
has_property(d200,salmonella,n).
has_property(d200,mouse_lymph,p).
has_property(d200,cytogen_ca,n).
has_property(d200,cytogen_sce,p).
has_property(d201,salmonella,n).
has_property(d201,cytogen_ca,n).
has_property(d201,cytogen_sce,p).
has_property(d202,salmonella,n).
has_property(d202,mouse_lymph,p).
has_property(d202,cytogen_ca,n).
has_property(d202,cytogen_sce,p).
has_property(d202,chromaberr,n).
has_property(d202,chromex,n).
has_property(d203,salmonella,n).
has_property(d203,mouse_lymph,n).
has_property(d203,cytogen_ca,n).
has_property(d203,chromex,p).
has_property(d204,salmonella,n).
has_property(d204,mouse_lymph,p).
has_property(d204,cytogen_ca,n).
has_property(d204,cytogen_sce,n).
has_property(d205,salmonella,p).
has_property(d205,mouse_lymph,p).
has_property(d205,drosophila_slrl,p).
has_property(d205,drosophila_rt,n).
has_property(d205,cytogen_ca,p).
has_property(d205,cytogen_sce,n).
has_property(d205,chromaberr,n).
has_property(d206,salmonella,n).
has_property(d206,mouse_lymph,n).
has_property(d206,cytogen_ca,n).
has_property(d206,cytogen_sce,n).
has_property(d207,salmonella,n).
has_property(d207,mouse_lymph,p).
has_property(d207,cytogen_ca,p).
has_property(d207,cytogen_sce,p).
has_property(d207,chromaberr,p).
has_property(d207,chromex,p).
has_property(d208_1,salmonella,n).
has_property(d208_1,cytogen_ca,n).
has_property(d208_1,cytogen_sce,p).
has_property(d208_2,salmonella,n).
has_property(d208_2,mouse_lymph,p).
has_property(d208_2,cytogen_sce,n).
has_property(d209,salmonella,n).
has_property(d209,mouse_lymph,p).
has_property(d209,cytogen_ca,p).
has_property(d209,cytogen_sce,p).
has_property(d211,salmonella,n).
has_property(d211,salmonella_n,n).
has_property(d211,mouse_lymph,p).
has_property(d211,cytogen_ca,n).
has_property(d211,cytogen_sce,p).
has_property(d212,salmonella,n).
has_property(d212,mouse_lymph,n).
has_property(d212,cytogen_ca,n).
has_property(d212,chromex,p).
has_property(d213,salmonella,n).
has_property(d213,mouse_lymph,p).
has_property(d213,cytogen_ca,p).
has_property(d213,cytogen_sce,p).
has_property(d213,chromex,p).
has_property(d214,salmonella,n).
has_property(d214,salmonella_n,n).
has_property(d214,mouse_lymph,p).
has_property(d214,cytogen_ca,n).
has_property(d214,cytogen_sce,p).
has_property(d215,salmonella,n).
has_property(d215,mouse_lymph,p).
has_property(d215,cytogen_ca,n).
has_property(d215,cytogen_sce,n).
has_property(d216,salmonella,p).
has_property(d216,cytogen_ca,n).
has_property(d216,cytogen_sce,n).
has_property(d217,salmonella,n).
has_property(d217,salmonella_n,n).
has_property(d217,mouse_lymph,p).
has_property(d217,cytogen_ca,n).
has_property(d217,cytogen_sce,p).
has_property(d218,salmonella,n).
has_property(d218,mouse_lymph,p).
has_property(d218,cytogen_ca,n).
has_property(d218,cytogen_sce,n).
has_property(d219,salmonella,n).
has_property(d219,mouse_lymph,p).
has_property(d219,cytogen_ca,p).
has_property(d219,cytogen_sce,n).
has_property(d221,salmonella,n).
has_property(d221,mouse_lymph,p).
has_property(d221,cytogen_ca,n).
has_property(d221,chromaberr,n).
has_property(d224,salmonella,n).
has_property(d224,mouse_lymph,n).
has_property(d224,cytogen_ca,n).
has_property(d224,cytogen_sce,n).
has_property(d225,salmonella,n).
has_property(d225,mouse_lymph,p).
has_property(d225,cytogen_ca,n).
has_property(d225,cytogen_sce,p).
has_property(d225,chromaberr,p).
has_property(d225,chromex,n).
has_property(d226,salmonella,p).
has_property(d226,salmonella_n,p).
has_property(d226,mouse_lymph,p).
has_property(d226,drosophila_slrl,p).
has_property(d226,drosophila_rt,n).
has_property(d226,cytogen_ca,p).
has_property(d226,cytogen_sce,p).
has_property(d227,salmonella,p).
has_property(d227,mouse_lymph,p).
has_property(d227,drosophila_slrl,p).
has_property(d227,drosophila_rt,p).
has_property(d227,cytogen_ca,p).
has_property(d227,cytogen_sce,p).
has_property(d227,chromaberr,n).
has_property(d228,salmonella,p).
has_property(d228,salmonella_n,p).
has_property(d228,mouse_lymph,p).
has_property(d228,drosophila_slrl,p).
has_property(d228,drosophila_rt,p).
has_property(d228,cytogen_ca,p).
has_property(d228,cytogen_sce,p).
has_property(d228,chromaberr,n).
has_property(d229,salmonella,p).
has_property(d229,cytogen_ca,p).
has_property(d229,cytogen_sce,p).
has_property(d229,micronuc_m,n).
has_property(d229,micronuc_f,n).
has_property(d230,salmonella,p).
has_property(d230,mouse_lymph,p).
has_property(d230,drosophila_slrl,p).
has_property(d230,drosophila_rt,n).
has_property(d230,cytogen_ca,n).
has_property(d230,cytogen_sce,p).
has_property(d230,chromaberr,p).
has_property(d231,salmonella,n).
has_property(d231,mouse_lymph,n).
has_property(d232,salmonella,p).
has_property(d232,mouse_lymph,p).
has_property(d232,drosophila_slrl,p).
has_property(d232,drosophila_rt,p).
has_property(d232,cytogen_ca,p).
has_property(d232,cytogen_sce,p).
has_property(d232,chromaberr,p).
has_property(d233,salmonella,n).
has_property(d233,cytogen_ca,n).
has_property(d233,cytogen_sce,p).
has_property(d234,salmonella,p).
has_property(d234,cytogen_ca,p).
has_property(d234,cytogen_sce,p).
has_property(d235,salmonella_n,p).
has_property(d236,salmonella,p).
has_property(d236,mouse_lymph,p).
has_property(d236,drosophila_slrl,p).
has_property(d236,drosophila_rt,n).
has_property(d236,cytogen_ca,p).
has_property(d236,cytogen_sce,p).
has_property(d236,chromaberr,p).
has_property(d236,chromex,p).
has_property(d237,salmonella,p).
has_property(d237,mouse_lymph,p).
has_property(d237,cytogen_ca,p).
has_property(d237,cytogen_sce,p).
has_property(d237,chromaberr,n).
has_property(d237,chromex,n).
has_property(d238,salmonella,p).
has_property(d238,mouse_lymph,p).
has_property(d238,drosophila_slrl,p).
has_property(d238,drosophila_rt,p).
has_property(d238,cytogen_ca,p).
has_property(d238,cytogen_sce,p).
has_property(d238,chromaberr,p).
has_property(d238,chromex,p).
has_property(d239,salmonella,n).
has_property(d239,cytogen_ca,n).
has_property(d239,cytogen_sce,p).
has_property(d240,salmonella,p).
has_property(d240,mouse_lymph,p).
has_property(d240,drosophila_slrl,p).
has_property(d240,drosophila_rt,p).
has_property(d240,cytogen_ca,p).
has_property(d240,cytogen_sce,p).
has_property(d241,salmonella,p).
has_property(d241,mouse_lymph,p).
has_property(d241,cytogen_ca,p).
has_property(d241,cytogen_sce,p).
has_property(d242,salmonella,p).
has_property(d242,mouse_lymph,p).
has_property(d242,cytogen_ca,p).
has_property(d242,cytogen_sce,p).
has_property(d243,salmonella,p).
has_property(d243,salmonella,p).
has_property(d243,mouse_lymph,p).
has_property(d243,cytogen_ca,p).
has_property(d243,cytogen_sce,p).
has_property(d243,chromaberr,n).
has_property(d243,chromex,n).
has_property(d244,salmonella,p).
has_property(d244,mouse_lymph,p).
has_property(d244,cytogen_ca,p).
has_property(d244,cytogen_sce,p).
has_property(d245,salmonella,p).
has_property(d245,salmonella_n,n).
has_property(d245,mouse_lymph,p).
has_property(d245,drosophila_slrl,p).
has_property(d245,drosophila_rt,p).
has_property(d245,cytogen_ca,p).
has_property(d245,cytogen_sce,p).
has_property(d247,salmonella,n).
has_property(d247,mouse_lymph,p).
has_property(d247,drosophila_slrl,p).
has_property(d247,drosophila_rt,n).
has_property(d247,cytogen_ca,p).
has_property(d247,cytogen_sce,p).
has_property(d248,salmonella_n,p).
has_property(d249,salmonella,p).
has_property(d250,salmonella,p).
has_property(d250,mouse_lymph,p).
has_property(d250,cytogen_ca,p).
has_property(d250,cytogen_sce,p).
has_property(d250,chromaberr,n).
has_property(d250,chromex,n).
has_property(d251,salmonella,n).
has_property(d251,cytogen_ca,n).
has_property(d252,salmonella,p).
has_property(d252,mouse_lymph,p).
has_property(d252,cytogen_ca,p).
has_property(d252,cytogen_sce,p).
has_property(d252,chromex,p).
has_property(d253,salmonella,n).
has_property(d253,mouse_lymph,p).
has_property(d253,drosophila_slrl,p).
has_property(d253,drosophila_rt,n).
has_property(d253,cytogen_ca,n).
has_property(d253,cytogen_sce,p).
has_property(d254,salmonella,p).
has_property(d254,drosophila_slrl,p).
has_property(d254,drosophila_rt,n).
has_property(d254,cytogen_ca,p).
has_property(d254,cytogen_sce,p).
has_property(d254,micronuc_m,n).
has_property(d254,micronuc_f,n).
has_property(d255,salmonella,p).
has_property(d256,salmonella,p).
has_property(d256,cytogen_ca,p).
has_property(d256,cytogen_sce,p).
has_property(d257,salmonella,n).
has_property(d257,cytogen_ca,n).
has_property(d257,cytogen_sce,p).
has_property(d258,salmonella,p).
has_property(d259,salmonella,n).
has_property(d259,cytogen_ca,p).
has_property(d259,cytogen_sce,n).
has_property(d260,salmonella,n).
has_property(d260,cytogen_ca,n).
has_property(d260,cytogen_sce,p).
has_property(d261,salmonella,n).
has_property(d261,cytogen_ca,n).
has_property(d261,cytogen_sce,n).
has_property(d262,salmonella,p).
has_property(d262,mouse_lymph,n).
has_property(d262,cytogen_ca,n).
has_property(d262,cytogen_sce,n).
has_property(d263,salmonella,p).
has_property(d263,mouse_lymph,p).
has_property(d263,cytogen_ca,p).
has_property(d263,cytogen_sce,p).
has_property(d263,chromaberr,n).
has_property(d263,chromex,n).
has_property(d264,salmonella,n).
has_property(d264,salmonella_n,n).
has_property(d264,mouse_lymph,n).
has_property(d264,cytogen_ca,n).
has_property(d264,cytogen_sce,n).
has_property(d265,salmonella,p).
has_property(d265,cytogen_sce,p).
has_property(d266,salmonella,n).
has_property(d266,mouse_lymph,p).
has_property(d266,cytogen_ca,n).
has_property(d266,cytogen_sce,p).
has_property(d266,chromaberr,n).
has_property(d267,salmonella,n).
has_property(d267,mouse_lymph,p).
has_property(d267,cytogen_ca,p).
has_property(d267,cytogen_sce,p).
has_property(d268,salmonella,p).
has_property(d268,mouse_lymph,p).
has_property(d268,drosophila_slrl,p).
has_property(d268,drosophila_rt,n).
has_property(d268,cytogen_ca,p).
has_property(d268,cytogen_sce,p).
has_property(d269,salmonella,n).
has_property(d269,salmonella_n,n).
has_property(d269,mouse_lymph,p).
has_property(d269,cytogen_ca,n).
has_property(d269,cytogen_sce,n).
has_property(d270,salmonella,p).
has_property(d270,mouse_lymph,n).
has_property(d270,cytogen_ca,n).
has_property(d270,cytogen_sce,p).
has_property(d271,salmonella,n).
has_property(d271,cytogen_ca,p).
has_property(d271,cytogen_sce,p).
has_property(d272,salmonella,p).
has_property(d272,cytogen_ca,n).
has_property(d272,cytogen_sce,n).
has_property(d273,salmonella,n).
has_property(d273,mouse_lymph,p).
has_property(d273,cytogen_ca,n).
has_property(d274,mouse_lymph,p).
has_property(d274,drosophila_slrl,p).
has_property(d274,drosophila_rt,n).
has_property(d274,cytogen_ca,n).
has_property(d274,cytogen_sce,p).
has_property(d274,chromaberr,n).
has_property(d274,chromex,p).
has_property(d275,salmonella,n).
has_property(d275,mouse_lymph,p).
has_property(d275,cytogen_ca,n).
has_property(d275,cytogen_sce,p).
has_property(d275,chromex,n).
has_property(d276,salmonella,p).
has_property(d276,cytogen_ca,n).
has_property(d276,cytogen_sce,p).
has_property(d277,salmonella,p).
has_property(d277,salmonella_n,n).
has_property(d277,mouse_lymph,p).
has_property(d277,cytogen_ca,n).
has_property(d277,cytogen_sce,n).
has_property(d278,salmonella,p).
has_property(d278,salmonella_n,p).
has_property(d278,mouse_lymph,p).
has_property(d278,cytogen_ca,p).
has_property(d278,cytogen_sce,p).
has_property(d279,salmonella,n).
has_property(d279,mouse_lymph,p).
has_property(d279,cytogen_ca,p).
has_property(d279,cytogen_sce,p).
has_property(d280,salmonella,p).
has_property(d280,mouse_lymph,p).
has_property(d280,cytogen_ca,n).
has_property(d280,cytogen_sce,p).
has_property(d281,salmonella,p).
has_property(d281,cytogen_ca,p).
has_property(d281,cytogen_sce,p).
has_property(d282,salmonella,p).
has_property(d282,salmonella_n,p).
has_property(d282,mouse_lymph,p).
has_property(d282,cytogen_ca,p).
has_property(d282,cytogen_sce,p).
has_property(d283,salmonella,p).
has_property(d283,mouse_lymph,p).
has_property(d283,cytogen_ca,p).
has_property(d283,cytogen_sce,p).
has_property(d283,chromaberr,n).
has_property(d283,chromex,n).
has_property(d284,salmonella,n).
has_property(d284,cytogen_ca,p).
has_property(d284,cytogen_sce,p).
has_property(d285,salmonella,p).
has_property(d285,mouse_lymph,p).
has_property(d285,cytogen_ca,p).
has_property(d285,cytogen_sce,p).
has_property(d286,salmonella,n).
has_property(d286,mouse_lymph,p).
has_property(d286,cytogen_ca,n).
has_property(d286,cytogen_sce,p).
has_property(d287,salmonella,p).
has_property(d287,cytogen_ca,p).
has_property(d287,cytogen_sce,p).
has_property(d288,salmonella,p).
has_property(d289,salmonella,n).
has_property(d289,mouse_lymph,p).
has_property(d289,drosophila_slrl,p).
has_property(d289,drosophila_rt,p).
has_property(d289,cytogen_ca,n).
has_property(d289,cytogen_sce,p).
has_property(d290,salmonella,p).
has_property(d290,cytogen_ca,p).
has_property(d290,cytogen_sce,p).
has_property(d291,salmonella,n).
has_property(d291,salmonella_n,n).
has_property(d291,mouse_lymph,n).
has_property(d291,cytogen_ca,n).
has_property(d291,cytogen_sce,n).
has_property(d292,salmonella,n).
has_property(d292,salmonella_n,n).
has_property(d292,cytogen_ca,n).
has_property(d292,cytogen_sce,n).
has_property(d293,salmonella,p).
has_property(d293,cytogen_ca,p).
has_property(d293,cytogen_sce,p).
has_property(d294,salmonella,p).
has_property(d294,mouse_lymph,p).
has_property(d294,cytogen_ca,p).
has_property(d294,cytogen_sce,p).
has_property(d294,chromaberr,n).
has_property(d294,chromex,n).
has_property(d295,salmonella,p).
has_property(d295,mouse_lymph,n).
has_property(d296,salmonella,n).
has_property(d296,cytogen_ca,p).
has_property(d296,cytogen_sce,p).
has_property(d297,salmonella,n).
has_property(d297,cytogen_ca,p).
has_property(d297,cytogen_sce,n).
has_property(d298,salmonella,n).
has_property(d298,cytogen_ca,n).
has_property(d299,salmonella,n).
has_property(d299,mouse_lymph,p).
has_property(d299,cytogen_ca,p).
has_property(d299,cytogen_sce,p).
has_property(d300,salmonella,n).
has_property(d300,cytogen_ca,p).
has_property(d300,cytogen_sce,p).
has_property(d301,salmonella,n).
has_property(d301,cytogen_ca,p).
has_property(d301,cytogen_sce,p).
has_property(d302,salmonella,n).
has_property(d302,mouse_lymph,p).
has_property(d302,cytogen_ca,n).
has_property(d302,cytogen_sce,p).
has_property(d303,salmonella,n).
has_property(d303,cytogen_ca,p).
has_property(d303,cytogen_sce,n).
has_property(d304,salmonella,n).
has_property(d304,cytogen_ca,n).
has_property(d304,cytogen_sce,n).
has_property(d305,salmonella,n).
has_property(d305,cytogen_ca,n).
has_property(d305,cytogen_sce,n).
has_property(d306,salmonella,n).
has_property(d306,cytogen_ca,p).
has_property(d307,salmonella,n).
has_property(d307,mouse_lymph,n).
has_property(d307,cytogen_ca,n).
has_property(d307,cytogen_sce,n).
has_property(d307,micronuc_m,n).
has_property(d307,micronuc_f,n).
has_property(d308,salmonella,n).
has_property(d308,cytogen_ca,n).
has_property(d308,cytogen_sce,p).
has_property(d308,micronuc_m,n).
has_property(d308,micronuc_f,n).
has_property(d309,salmonella,n).
has_property(d309,mouse_lymph,n).
has_property(d309,cytogen_ca,n).
has_property(d309,cytogen_sce,n).
has_property(d310,salmonella,n).
has_property(d310,mouse_lymph,p).
has_property(d310,cytogen_ca,p).
has_property(d310,cytogen_sce,p).
has_property(d311,salmonella,n).
has_property(d311,cytogen_ca,p).
has_property(d311,cytogen_sce,p).
has_property(d312,salmonella,n).
has_property(d312,cytogen_ca,n).
has_property(d312,cytogen_sce,p).
has_property(d312,micronuc_m,p).
has_property(d312,micronuc_f,n).
has_property(d312,chromaberr,n).
has_property(d313,salmonella,n).
has_property(d313,cytogen_ca,n).
has_property(d313,cytogen_sce,p).
has_property(d314,salmonella,n).
has_property(d314,cytogen_ca,n).
has_property(d314,cytogen_sce,p).
has_property(d315,salmonella,n).
has_property(d315,mouse_lymph,n).
has_property(d315,cytogen_ca,n).
has_property(d315,cytogen_sce,p).
has_property(d315,chromaberr,n).
has_property(d316,salmonella,p).
has_property(d316,mouse_lymph,p).
has_property(d316,cytogen_ca,n).
has_property(d316,cytogen_sce,p).
has_property(d318,salmonella,n).
has_property(d318,cytogen_ca,n).
has_property(d318,cytogen_sce,n).
has_property(d319,salmonella,p).
has_property(d319,micronuc_m,p).
has_property(d319,micronuc_f,p).
has_property(d320,salmonella,p).
has_property(d320,cytogen_ca,p).
has_property(d320,cytogen_sce,p).
has_property(d320,micronuc_m,n).
has_property(d320,micronuc_f,n).
has_property(d321,salmonella,p).
has_property(d321,salmonella_n,p).
has_property(d321,cytogen_ca,n).
has_property(d321,cytogen_sce,p).
has_property(d322,salmonella,n).
has_property(d322,salmonella_reduc,n).
has_property(d322,cytogen_ca,n).
has_property(d322,cytogen_sce,p).
has_property(d323,salmonella,p).
has_property(d323,cytogen_ca,n).
has_property(d323,cytogen_sce,n).
has_property(d324,salmonella,p).
has_property(d324,cytogen_ca,n).
has_property(d324,cytogen_sce,p).
has_property(d325,salmonella,p).
has_property(d325,mouse_lymph,p).
has_property(d325,cytogen_ca,n).
has_property(d325,cytogen_sce,n).
has_property(d326,salmonella,n).
has_property(d326,cytogen_ca,p).
has_property(d326,cytogen_sce,p).
has_property(d327,salmonella,n).
has_property(d327,cytogen_ca,n).
has_property(d327,cytogen_sce,n).
has_property(d327,micronuc_m,p).
has_property(d327,micronuc_f,p).
has_property(d328,salmonella,p).
has_property(d328,salmonella_n,n).
has_property(d328,cytogen_ca,n).
has_property(d328,cytogen_sce,n).
has_property(d329,salmonella,p).
has_property(d329,salmonella_reduc,p).
has_property(d329,cytogen_ca,n).
has_property(d329,cytogen_sce,n).
has_property(d330,salmonella,n).
has_property(d330,salmonella_reduc,p).
has_property(d330,cytogen_ca,n).
has_property(d330,cytogen_sce,n).
has_property(d331,salmonella,p).
has_property(d331,cytogen_ca,p).
has_property(d331,cytogen_sce,p).
has_property(d331,micronuc_m,n).
has_property(d331,micronuc_f,n).
has_property(d332,salmonella,p).
has_property(d332,mouse_lymph,p).
has_property(d332,drosophila_slrl,p).
has_property(d332,drosophila_rt,p).
has_property(d332,cytogen_ca,p).
has_property(d332,cytogen_sce,p).
has_property(d333,salmonella,p).
has_property(d333,salmonella_reduc,p).
has_property(d333,mouse_lymph,p).
has_property(d333,cytogen_ca,p).
has_property(d333,cytogen_sce,p).
has_property(d335,salmonella,p).
has_property(d335,mouse_lymph,p).
has_property(d335,cytogen_ca,p).
has_property(d335,cytogen_sce,p).
has_property(d336,salmonella,p).
has_property(d336,mouse_lymph,p).
has_property(d336,cytogen_ca,p).
has_property(d336,cytogen_sce,p).
has_property(d337,salmonella,p).
has_property(d337,mouse_lymph,p).
has_property(d337,cytogen_ca,p).
has_property(d337,cytogen_sce,p).
% recent addition (21/04/97): following error detected in CAS entry for d334
has_property(d334,salmonella,p).
has_property(d334,drosophila_slrl,p).
has_property(d334,drosophila_rt,n).
has_property(d334,cytogen_ca,n).
has_property(d334,cytogen_sce,p).
