
package org.dllearner.server.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0_02
 * 
 */
@XmlRootElement(name = "OntologyURLNotValid", namespace = "http://ws/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OntologyURLNotValid", namespace = "http://ws/", propOrder = {
    "detail",
    "message"
})
public class OntologyURLNotValidBean {

    private String detail;
    private String message;

    /**
     * 
     * @return
     *     returns String
     */
    public String getDetail() {
        return this.detail;
    }

    /**
     * 
     * @param detail
     *     the value for the detail property
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * 
     * @param message
     *     the value for the message property
     */
    public void setMessage(String message) {
        this.message = message;
    }

}
