name: Java CI

on: 
  push:
    branches:
    - develop
  

jobs:
  build:
    name: Build on Java ${{ matrix.java_version }} and ${{ matrix.os }}
    strategy:
      matrix:
        java_version: ['1.8', '9.0.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java_version }}
        architecture: x64
    - name: Build with Maven
      run: mvn compile --file pom.xml
